<a href="https://colab.research.google.com/github/gumurytv/bigdataCert/blob/main/PART1_%EC%B1%95%ED%84%B002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
menu=pd.Series(['비빔밥','김치찌개','된장찌개'])
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [3]:
price=pd.Series([10000,9000,8000])
price

0    10000
1     9000
2     8000
dtype: int64

In [6]:
pd.DataFrame({
    '메뉴':menu,
    '가격':price
})

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [8]:
df=pd.DataFrame({
    '메뉴':['비빔밥','김치찌개','된장찌개'],
    '가격':[10000,9000,8000],
    '원산지':['국내산','국내산','국내산']})
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [9]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [10]:
df[['메뉴']]

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [11]:
df[['메뉴','가격']]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [12]:
cols=['메뉴','가격']

In [13]:
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [14]:
print('df:',type(df))
print('df:',type(df['가격']))
print('df:',type(df[['가격']]))

df: <class 'pandas.core.frame.DataFrame'>
df: <class 'pandas.core.series.Series'>
df: <class 'pandas.core.frame.DataFrame'>

In [16]:
df=pd.DataFrame({
    '메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    '가격':[4500,5000,5500,5000,4000,5900,5300],
    '칼로리':[10,110,250,110,20,210,0]
})
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [17]:
df.to_csv('temp.csv')

In [18]:
temp_df=pd.read_csv('temp.csv')

In [19]:
temp_df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [20]:
df.to_csv('cafe.csv',index=False)

In [21]:
df=pd.read_csv('cafe.csv')

In [22]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [23]:
df=pd.read_csv('cafe.csv',encoding='cp949')

UnicodeDecodeError: 'cp949' codec can't decode byte 0x80 in position 9: illegal multibyte sequence

In [24]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [25]:
df.tail

<bound method NDFrame.tail of       메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0>

In [26]:
df.tail()

      메뉴    가격  칼로리
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [27]:
df.head(3)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250

In [28]:
df.shape

(7, 3)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [31]:
df.corr()

ValueError: could not convert string to float: '아메리카노'

In [33]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [34]:
df.corr()

ValueError: could not convert string to float: '아메리카노'

In [37]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [38]:
df_car=pd.DataFrame({
    'car':['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
    'size':['S','M','S','S','M','M','L','S','S','M','S']})
df_car

      car size
0   Sedan    S
1     SUV    M
2   Sedan    S
3     SUV    S
4     SUV    M
5     SUV    M
6   Sedan    L
7   Sedan    S
8   Sedan    S
9   Sedan    M
10  Sedan    S

In [40]:
df_car.nunique()

car     2
size    3
dtype: int64

In [41]:
df_car['car'].unique()

array(['Sedan', 'SUV'], dtype=object)

In [42]:
print('car:',df_car['car'].unique())

car: ['Sedan' 'SUV']

In [43]:
df_car.value_count()

AttributeError: 'DataFrame' object has no attribute 'value_count'

In [44]:
df_car.value_counts()

car    size
Sedan  S       5
SUV    M       3
       S       1
Sedan  L       1
       M       1
Name: count, dtype: int64

In [45]:
df_car['car'].value_counts()

car
Sedan    7
SUV      4
Name: count, dtype: int64

In [46]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [48]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [49]:
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [50]:
df_car.describe(include='O')

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [51]:
df.describe(include='O')

           메뉴
count       7
unique      7
top     아메리카노
freq        1