<a href="https://colab.research.google.com/github/gumurytv/bigdataCert/blob/main/PART1_%EC%B1%95%ED%84%B03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import pandas as pd

In [110]:
import numpy as np

In [111]:
df=pd.DataFrame({'메뉴':['아메리카노','카페라떼','에스프레소','카페모카','바닐라라떼'],
                 '가격':[4500,5000,4000,5000,5300],
                 '칼로리':[10,110,np.nan,210,np.nan],
                 '원두':['과테말라','브라질','과테말라',np.nan,np.nan]})

In [112]:
df

      메뉴    가격    칼로리    원두
0  아메리카노  4500   10.0  과테말라
1   카페라떼  5000  110.0   브라질
2  에스프레소  4000    NaN  과테말라
3   카페모카  5000  210.0   NaN
4  바닐라라떼  5300    NaN   NaN

In [113]:
df['칼로리']=df['칼로리'].fillna(df['칼로리'].min())

In [114]:
df

      메뉴    가격    칼로리    원두
0  아메리카노  4500   10.0  과테말라
1   카페라떼  5000  110.0   브라질
2  에스프레소  4000   10.0  과테말라
3   카페모카  5000  210.0   NaN
4  바닐라라떼  5300   10.0   NaN

In [115]:
df['원두']=df['원두'].fillna(df['원두'].mode()[0])

In [116]:
df

      메뉴    가격    칼로리    원두
0  아메리카노  4500   10.0  과테말라
1   카페라떼  5000  110.0   브라질
2  에스프레소  4000   10.0  과테말라
3   카페모카  5000  210.0  과테말라
4  바닐라라떼  5300   10.0  과테말라

In [117]:
sum(df['가격']>=5000)

3

In [118]:
df['이벤트가']=df['가격']*0.5

In [119]:
df

      메뉴    가격    칼로리    원두    이벤트가
0  아메리카노  4500   10.0  과테말라  2250.0
1   카페라떼  5000  110.0   브라질  2500.0
2  에스프레소  4000   10.0  과테말라  2000.0
3   카페모카  5000  210.0  과테말라  2500.0
4  바닐라라떼  5300   10.0  과테말라  2650.0

In [120]:
df['이벤트가']=df['이벤트가'].astype(int)

In [121]:
df

      메뉴    가격    칼로리    원두  이벤트가
0  아메리카노  4500   10.0  과테말라  2250
1   카페라떼  5000  110.0   브라질  2500
2  에스프레소  4000   10.0  과테말라  2000
3   카페모카  5000  210.0  과테말라  2500
4  바닐라라떼  5300   10.0  과테말라  2650

In [122]:
df

      메뉴    가격    칼로리    원두  이벤트가
0  아메리카노  4500   10.0  과테말라  2250
1   카페라떼  5000  110.0   브라질  2500
2  에스프레소  4000   10.0  과테말라  2000
3   카페모카  5000  210.0  과테말라  2500
4  바닐라라떼  5300   10.0  과테말라  2650

In [123]:
df

      메뉴    가격    칼로리    원두  이벤트가
0  아메리카노  4500   10.0  과테말라  2250
1   카페라떼  5000  110.0   브라질  2500
2  에스프레소  4000   10.0  과테말라  2000
3   카페모카  5000  210.0  과테말라  2500
4  바닐라라떼  5300   10.0  과테말라  2650

In [124]:
df

      메뉴    가격    칼로리    원두  이벤트가
0  아메리카노  4500   10.0  과테말라  2250
1   카페라떼  5000  110.0   브라질  2500
2  에스프레소  4000   10.0  과테말라  2000
3   카페모카  5000  210.0  과테말라  2500
4  바닐라라떼  5300   10.0  과테말라  2650

In [125]:
df.drop('칼로리',axis=1,inplace=True)

In [126]:
df

      메뉴    가격    원두  이벤트가
0  아메리카노  4500  과테말라  2250
1   카페라떼  5000   브라질  2500
2  에스프레소  4000  과테말라  2000
3   카페모카  5000  과테말라  2500
4  바닐라라떼  5300  과테말라  2650

In [127]:
df.loc[:3]

      메뉴    가격    원두  이벤트가
0  아메리카노  4500  과테말라  2250
1   카페라떼  5000   브라질  2500
2  에스프레소  4000  과테말라  2000
3   카페모카  5000  과테말라  2500

In [128]:
df.loc[:2]

      메뉴    가격    원두  이벤트가
0  아메리카노  4500  과테말라  2250
1   카페라떼  5000   브라질  2500
2  에스프레소  4000  과테말라  2000

In [129]:
df.iloc[0:3]

      메뉴    가격    원두  이벤트가
0  아메리카노  4500  과테말라  2250
1   카페라떼  5000   브라질  2500
2  에스프레소  4000  과테말라  2000

In [130]:
df.loc[0:1]

      메뉴    가격    원두  이벤트가
0  아메리카노  4500  과테말라  2250
1   카페라떼  5000   브라질  2500

In [131]:
df.iloc[0:1]

      메뉴    가격    원두  이벤트가
0  아메리카노  4500  과테말라  2250

In [132]:
df

      메뉴    가격    원두  이벤트가
0  아메리카노  4500  과테말라  2250
1   카페라떼  5000   브라질  2500
2  에스프레소  4000  과테말라  2000
3   카페모카  5000  과테말라  2500
4  바닐라라떼  5300  과테말라  2650

In [133]:
df.loc[1:2,['메뉴','가격']]

      메뉴    가격
1   카페라떼  5000
2  에스프레소  4000

In [134]:
df.iloc[1:3,:2]

      메뉴    가격
1   카페라떼  5000
2  에스프레소  4000

In [135]:
df=df.sort_values('가격',ascending=False)

In [136]:
df.iloc[:3]

      메뉴    가격    원두  이벤트가
4  바닐라라떼  5300  과테말라  2650
3   카페모카  5000  과테말라  2500
1   카페라떼  5000   브라질  2500

In [137]:
df=df.sort_values('가격',ascending=False)

In [138]:
df

      메뉴    가격    원두  이벤트가
4  바닐라라떼  5300  과테말라  2650
3   카페모카  5000  과테말라  2500
1   카페라떼  5000   브라질  2500
0  아메리카노  4500  과테말라  2250
2  에스프레소  4000  과테말라  2000

In [139]:
import pandas as pd
import numpy as np

In [140]:
df=pd.read_csv('type1_data1.csv')

In [141]:
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [142]:
df['f5']==0

0      False
1      False
2      False
3      False
4      False
       ...
115     True
116     True
117     True
118     True
119     True
Name: f5, Length: 120, dtype: bool

In [143]:
cond=df['f5']==0

In [144]:
df[~cond]

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

In [145]:
df[cond]

        id   age city    f1  f2      f3    f4   f5  subscribed    views
102  id101  36.0   경기  65.0   0  silver  ISFP  0.0  2025-01-29   5735.0
103  id102  43.0   대구  34.0   0     NaN  ISFP  0.0  2025-01-30   8765.0
104  id103  21.0   부산  53.0   0     vip  ISFP  0.0  2025-02-17  13543.0
105  id104  21.0   서울  13.0   0  silver  ESFJ  0.0  2025-02-17   4556.0
106  id105  21.0   경기  24.0   0    gold  ESFJ  0.0  2025-02-17   7654.0
107  id106  21.0   대구  65.0   0     vip  INFP  0.0  2025-02-17   4212.0
108  id107  21.0   부산  76.0   1  silver  ESTJ  0.0  2025-02-17   2346.0
109  id108  21.0   서울  54.0   1    gold  ESTJ  0.0  2025-02-17   2178.0
110  id109  21.0   경기  78.0   1     vip  ESTJ  0.0  2025-02-17   6790.0
111  id110  22.0   대구  45.0   2  silver  ESTJ  0.0  2025-02-17   2112.0
112  id111  22.0   부산  65.0   2    gold  ENTP  0.0  2025-02-17   7894.0
113  id112  22.0   서울  45.0   2     vip  ENTP  0.0  2025-02-17   9877.0
114  id113  22.0   경기  34.0   2  silver  ENTP  0.0  2025-02-17  10346.0
115  id114  22.0   대구  23.0   0    gold  INTP  0.0  2025-02-17   9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP  0.0  2025-02-17   5628.0
117  id116  23.0   서울  12.0   1  silver  INFP  0.0  2025-02-17   1267.0
118  id117  23.0   대구  65.0   2    gold  INFP  0.0  2025-02-17   6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ  0.0  2025-02-17   2356.0

In [146]:
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [147]:
df['views']=df['views'].fillna(df['views'].min())

In [148]:
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [149]:
df.describe()

              age          f1          f2          f5        views
count  120.000000   89.000000  120.000000  120.000000    120.00000
mean    46.727500   62.528090    0.683333   48.122075   5889.47500
std     29.520826   21.021142    0.744541   33.034928   4195.92205
min    -13.500000   12.000000    0.000000    0.000000     42.00000
25%     22.000000   50.000000    0.000000   17.252986   2711.75000
50%     42.000000   62.000000    1.000000   52.667078   5924.00000
75%     74.250000   77.000000    1.000000   75.224368   8355.50000
max    100.000000  111.000000    2.000000   98.429899  21550.00000

In [150]:
df.isnull().sum()

id             0
age            0
city           0
f1            31
f2             0
f3            29
f4             0
f5             0
subscribed     0
views          0
dtype: int64

In [151]:
float(df['views'].median())

5924.0

In [152]:
import pandas as pd

In [153]:
df=pd.read_csv('type1_data1.csv')

In [154]:
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [155]:
df.head(5)

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [157]:
df=df['subscribed'].value_counts()

In [158]:
df

subscribed
2025-02-17    16
2024-06-21     3
2024-07-16     2
2024-04-03     2
2024-02-09     2
              ..
2024-05-06     1
2024-10-02     1
2024-12-02     1
2025-01-29     1
2025-01-30     1
Name: count, Length: 96, dtype: int64

In [159]:
df.index[0][-2:]

'17'

In [160]:
df=pd.read_csv('type1_data1.csv')

In [161]:
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [163]:
df.isnull().sum()

id             0
age            0
city           0
f1            31
f2             0
f3            29
f4             0
f5             0
subscribed     0
views          4
dtype: int64

In [164]:
df.dropna()

        id   age city     f1  f2      f3    f4         f5  subscribed    views
2     id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5     id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7     id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9     id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10   id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
..     ...   ...  ...    ...  ..     ...   ...        ...         ...      ...
115  id114  22.0   대구   23.0   0    gold  INTP   0.000000  2025-02-17   9747.0
116  id115  23.0   부산   65.0   0     vip  ENTP   0.000000  2025-02-17   5628.0
117  id116  23.0   서울   12.0   1  silver  INFP   0.000000  2025-02-17   1267.0
118  id117  23.0   대구   65.0   2    gold  INFP   0.000000  2025-02-17   6543.0
119  id118  24.0   부산   94.0   1     vip  ESFJ   0.000000  2025-02-17   2356.0

[70 rows x 10 columns]

In [165]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [166]:
df=df.dropna()

In [167]:
df

        id   age city     f1  f2      f3    f4         f5  subscribed    views
2     id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5     id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7     id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9     id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10   id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
..     ...   ...  ...    ...  ..     ...   ...        ...         ...      ...
115  id114  22.0   대구   23.0   0    gold  INTP   0.000000  2025-02-17   9747.0
116  id115  23.0   부산   65.0   0     vip  ENTP   0.000000  2025-02-17   5628.0
117  id116  23.0   서울   12.0   1  silver  INFP   0.000000  2025-02-17   1267.0
118  id117  23.0   대구   65.0   2    gold  INFP   0.000000  2025-02-17   6543.0
119  id118  24.0   부산   94.0   1     vip  ESFJ   0.000000  2025-02-17   2356.0

[70 rows x 10 columns]

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 2 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          70 non-null     object
 1   age         70 non-null     float64
 2   city        70 non-null     object
 3   f1          70 non-null     float64
 4   f2          70 non-null     int64
 5   f3          70 non-null     object
 6   f4          70 non-null     object
 7   f5          70 non-null     float64
 8   subscribed  70 non-null     object
 9   views       70 non-null     float64
dtypes: float64(4), int64(1), object(5)
memory usage: 8.1+ KB

In [169]:
df['new']=df['views']/df['f1']

/tmp/ipykernel_2415/3348704942.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['new']=df['views']/df['f1']

In [170]:
df

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
2,id03,27.0,서울,61.0,1,gold,ISTJ,17.252986,2024-03-16,7312.0,119.868852
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,32.277228
9,id10,95.0,서울,74.0,1,gold,ISFP,98.429899,2024-04-03,9992.0,135.027027
10,id100,47.0,경기,53.0,0,vip,ESFP,33.308999,2024-02-21,15535.0,293.113208
...,...,...,...,...,...,...,...,...,...,...,...
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,9747.0,423.782609
116,id115,23.0,부산,65.0,0,vip,ENTP,0.000000,2025-02-17,5628.0,86.584615
117,id116,23.0,서울,12.0,1,silver,INFP,0.000000,2025-02-17,1267.0,105.583333
118,id117,23.0,대구,65.0,2,gold,INFP,0.000000,2025-02-17,6543.0,100.661538
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,2356.0,25.063830

In [180]:
df=df.sort_values('new',ascending=False)

In [181]:
df

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,9747.0,423.782609
83,id83,73.0,경기,50.0,1,vip,ENTP,80.138280,2024-09-26,19139.0,382.780000
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
105,id104,21.0,서울,13.0,0,silver,ESFJ,0.000000,2025-02-17,4556.0,350.461538
106,id105,21.0,경기,24.0,0,gold,ESFJ,0.000000,2025-02-17,7654.0,318.916667
...,...,...,...,...,...,...,...,...,...,...,...
109,id108,21.0,서울,54.0,1,gold,ESTJ,0.000000,2025-02-17,2178.0,40.333333
57,id57,3.0,대구,111.0,0,silver,ISFJ,29.269869,2024-01-12,4421.0,39.828829
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,32.277228
108,id107,21.0,부산,76.0,1,silver,ESTJ,0.000000,2025-02-17,2346.0,30.868421
119,id118,24.0,부산,94.0,1,vip,ESFJ,0.000000,2025-02-17,2356.0,25.063830

In [184]:
int(df.iloc[0,1])

22

In [186]:
df=pd.read_csv('type1_data1.csv')

In [187]:
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

In [189]:
df['views']=df['views'].fillna(0)

In [190]:
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

In [191]:
int(sum(df['views']))

706569

In [192]:
df=df.sort_values('views',ascending=False)

In [193]:
df

       id   age city    f1  f2   f3    f4         f5  subscribed    views
5    id06  22.0   서울  57.0   0  vip  INTP  20.129444  2024-09-12  21550.0
56   id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2024-04-05  19589.0
83   id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2024-09-26  19139.0
32   id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2024-05-24  17421.0
10  id100  47.0   경기  53.0   0  vip  ESFP  33.308999  2024-02-21  15535.0
..    ...   ...  ...   ...  ..  ...   ...        ...         ...      ...
93   id93  21.8   경기  57.0   0  NaN  ISFP  73.586397  2024-06-07     42.0
48   id48  18.0   대구   NaN   0  NaN  ENFP  20.129444  2024-03-25      0.0
39   id39  56.0   부산  50.0   0  NaN  INFJ  33.308999  2024-12-22      0.0
20   id20  11.0   서울  51.0   1  NaN  INTJ  91.297791  2024-07-16      0.0
82   id82  48.0   경기   NaN   0  NaN  ENTJ  37.113739  2024-10-17      0.0

[120 rows x 10 columns]

In [194]:
df.head(10)

        id   age city    f1  f2      f3    f4         f5  subscribed    views
5     id06  22.0   서울  57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
56    id56  59.0   대구   NaN   1     vip  ESTJ  73.586397  2024-04-05  19589.0
83    id83  73.0   경기  50.0   1     vip  ENTP  80.138280  2024-09-26  19139.0
32    id32  25.0   부산  64.0   0     vip  ISFJ  13.049921  2024-05-24  17421.0
10   id100  47.0   경기  53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
100  id100  47.0   경기  53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0
104  id103  21.0   부산  53.0   0     vip  ISFP   0.000000  2025-02-17  13543.0
114  id113  22.0   경기  34.0   2  silver  ENTP   0.000000  2025-02-17  10346.0
9     id10  95.0   서울  74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
113  id112  22.0   서울  45.0   2     vip  ENTP   0.000000  2025-02-17   9877.0

In [196]:
df.iloc[9,9]

np.float64(9877.0)

In [197]:
view_min=df.iloc[:10]['views'].min()
df.iloc[:10,-1]=view_min

In [198]:
df

       id   age city    f1  f2   f3    f4         f5  subscribed   views
5    id06  22.0   서울  57.0   0  vip  INTP  20.129444  2024-09-12  9877.0
56   id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2024-04-05  9877.0
83   id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2024-09-26  9877.0
32   id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2024-05-24  9877.0
10  id100  47.0   경기  53.0   0  vip  ESFP  33.308999  2024-02-21  9877.0
..    ...   ...  ...   ...  ..  ...   ...        ...         ...     ...
93   id93  21.8   경기  57.0   0  NaN  ISFP  73.586397  2024-06-07    42.0
48   id48  18.0   대구   NaN   0  NaN  ENFP  20.129444  2024-03-25     0.0
39   id39  56.0   부산  50.0   0  NaN  INFJ  33.308999  2024-12-22     0.0
20   id20  11.0   서울  51.0   1  NaN  INTJ  91.297791  2024-07-16     0.0
82   id82  48.0   경기   NaN   0  NaN  ENTJ  37.113739  2024-10-17     0.0

[120 rows x 10 columns]

In [199]:
int(sum(df['views']))

652812