<a href="https://colab.research.google.com/github/gumurytv/bigdataCert/blob/main/PART1_%EC%B1%95%ED%84%B002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [145]:
import pandas as pd

In [146]:
menu=pd.Series(['비빔밥','김치찌개','된장찌개'])
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [147]:
price=pd.Series([10000,9000,8000])
price

0    10000
1     9000
2     8000
dtype: int64

In [148]:
pd.DataFrame({
    '메뉴':menu,
    '가격':price
})

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [149]:
df=pd.DataFrame({
    '메뉴':['비빔밥','김치찌개','된장찌개'],
    '가격':[10000,9000,8000],
    '원산지':['국내산','국내산','국내산']})
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [150]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [151]:
df[['메뉴']]

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [152]:
df[['메뉴','가격']]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [153]:
cols=['메뉴','가격']

In [154]:
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [155]:
print('df:',type(df))
print('df:',type(df['가격']))
print('df:',type(df[['가격']]))

df: <class 'pandas.core.frame.DataFrame'>
df: <class 'pandas.core.series.Series'>
df: <class 'pandas.core.frame.DataFrame'>

In [156]:
df=pd.DataFrame({
    '메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    '가격':[4500,5000,5500,5000,4000,5900,5300],
    '칼로리':[10,110,250,110,20,210,0]
})
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [157]:
df.to_csv('temp.csv')

In [158]:
temp_df=pd.read_csv('temp.csv')

In [159]:
temp_df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [160]:
df.to_csv('cafe.csv',index=False)

In [161]:
df=pd.read_csv('cafe.csv')

In [162]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [163]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [164]:
df.tail

<bound method NDFrame.tail of       메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0>

In [165]:
df.tail()

      메뉴    가격  칼로리
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [166]:
df.head(3)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250

In [167]:
df.shape

(7, 3)

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [169]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [170]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [171]:
df_car=pd.DataFrame({
    'car':['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
    'size':['S','M','S','S','M','M','L','S','S','M','S']})
df_car

      car size
0   Sedan    S
1     SUV    M
2   Sedan    S
3     SUV    S
4     SUV    M
5     SUV    M
6   Sedan    L
7   Sedan    S
8   Sedan    S
9   Sedan    M
10  Sedan    S

In [172]:
df_car.nunique()

car     2
size    3
dtype: int64

In [173]:
df_car['car'].unique()

array(['Sedan', 'SUV'], dtype=object)

In [174]:
print('car:',df_car['car'].unique())

car: ['Sedan' 'SUV']

In [175]:
df_car['car'].value_counts()

car
Sedan    7
SUV      4
Name: count, dtype: int64

In [176]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [177]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [178]:
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [179]:
df_car.describe(include='O')

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [180]:
df.describe(include='O')

           메뉴
count       7
unique      7
top     아메리카노
freq        1

In [181]:
data={'메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
      '가격':[4500.0,5000.0,5500.0,5000.0,4000.0,5900.0,5300.0,],
      '칼로리':['10','110','250','110','20','210','0']}

In [182]:
df=pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [183]:
df['가격']=df['가격'].astype('int')

In [184]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [185]:
df['칼로리']=df['칼로리'].astype('float')

In [186]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [187]:
df.head()

      메뉴    가격    칼로리
0  아메리카노  4500   10.0
1   카페라떼  5000  110.0
2   카페모카  5500  250.0
3   카푸치노  5000  110.0
4  에스프레소  4000   20.0

In [188]:
df=pd.read_csv('cafe.csv')

In [189]:
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [190]:
df['new']=0

In [191]:
df.head()

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0
2   카페모카  5500  250    0
3   카푸치노  5000  110    0
4  에스프레소  4000   20    0

In [192]:
discount=0.2
df['할인가']=df['가격']*(1-discount)
df.head()

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0
4  에스프레소  4000   20    0  3200.0

In [193]:
df=pd.read_csv('cafe.csv')

In [194]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [195]:
df.drop(1,axis=0,inplace=True)
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210

In [196]:
df=df.drop('가격',axis=1)

In [197]:
df.head()

      메뉴  칼로리
0  아메리카노   10
2   카페모카  250
3   카푸치노  110
4  에스프레소   20
5    밀크티  210

In [198]:
df=pd.read_csv('cafe.csv')

In [199]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [200]:
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [201]:
df.loc[1,'가격']

np.int64(5000)

In [202]:
df.loc[1,'칼로리']

np.int64(110)

In [203]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [204]:
df.loc[2,'가격':'칼로리']

가격     5500
칼로리     250
Name: 2, dtype: object

In [205]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [206]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [207]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [208]:
df=pd.read_csv('cafe.csv')

In [209]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [210]:
import numpy as np

In [211]:
df['원산지']=np.nan

In [212]:
df.head()

      메뉴    가격  칼로리  원산지
0  아메리카노  4500   10  NaN
1   카페라떼  5000  110  NaN
2   카페모카  5500  250  NaN
3   카푸치노  5000  110  NaN
4  에스프레소  4000   20  NaN

In [213]:
df.loc[0,'원산지']='콜롬비아'
df.loc[2:3,'원산지']='과테말라'

/tmp/ipykernel_190/3061043173.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0,'원산지']='콜롬비아'

In [214]:
df.head()

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN

In [215]:
df.loc['시즌']=['크리스마스라떼',6000,300,'한국']

In [216]:
df.tail()

         메뉴    가격  칼로리   원산지
3      카푸치노  5000  110  과테말라
4     에스프레소  4000   20   NaN
5       밀크티  5900  210   NaN
6        녹차  5300    0   NaN
시즌  크리스마스라떼  6000  300    한국

In [217]:
df.loc[7]={'메뉴':'딴짓커피','가격':2000,'칼로리':20}

In [218]:
df.tail(3)

         메뉴    가격  칼로리  원산지
6        녹차  5300    0  NaN
시즌  크리스마스라떼  6000  300   한국
7      딴짓커피  2000   20  NaN

In [219]:
df=df.drop('시즌',axis=0)

In [220]:
df

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [221]:
df.to_csv('cafe2.csv',index=False)

In [222]:
df=pd.read_csv('cafe2.csv')

In [ ]:
df.sort_index(ascending=False)

In [ ]:
df.sort_values('메뉴',ascending=False)

In [ ]:
df.sort_values(['가격','메뉴'],ascending=[False,True],inplace=True)

In [ ]:
df.head()

In [ ]:
df.reset_index(drop=True)

In [ ]:
df=pd.read_csv('cafe2.csv')

In [ ]:
df.head()

In [ ]:
df['칼로리']<50

In [ ]:
cond=df['칼로리']<50

In [ ]:
df[cond]

In [ ]:
df[~cond]

In [ ]:
df[~cond]

In [224]:
df=pd.read_csv('cafe2.csv')

In [225]:
df.head()

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN

In [226]:
df['칼로리']<50

0     True
1    False
2    False
3    False
4     True
5    False
6     True
7     True
Name: 칼로리, dtype: bool

In [227]:
df['칼로리']

0     10
1    110
2    250
3    110
4     20
5    210
6      0
7     20
Name: 칼로리, dtype: int64

In [228]:
cond1=df['가격']>=5000
cond2=df['칼로리']>100
df[cond1&cond2]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN

In [229]:
df[cond1|cond2]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN
6    녹차  5300    0   NaN

In [231]:
df[df['원산지']=='과테말라']

     메뉴    가격  칼로리   원산지
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라

In [237]:
cond1=df['원산지']=='과테말라'
cond2=df['가격']<=5000

In [238]:
df[cond1&cond2]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  과테말라
1   카페라떼  5000  110  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20  과테말라
7   딴짓커피  2000   20  과테말라

In [239]:
df['메뉴'].isin(['녹차'])

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
Name: 메뉴, dtype: bool

In [240]:
cond=df['메뉴'].isin(['녹차'])

In [241]:
cond

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
Name: 메뉴, dtype: bool

In [242]:
df[cond]

   메뉴    가격  칼로리   원산지
6  녹차  5300    0  과테말라

In [243]:
box=['녹차','카푸치노','카페라떼']

In [244]:
cond=df['메뉴'].isin(box)

In [245]:
cond

0    False
1     True
2    False
3     True
4    False
5    False
6     True
7    False
Name: 메뉴, dtype: bool

In [246]:
df[cond]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110  과테말라
3  카푸치노  5000  110  과테말라
6    녹차  5300    0  과테말라

In [247]:
df=pd.read_csv('cafe2.csv')

In [248]:
df

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라
4  에스프레소  4000   20   NaN
5    밀크티  5900  210   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [249]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False   True

In [250]:
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [251]:
df.isna().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [253]:
df['원산지'].fillna('코스타리카',inplace=True)

In [254]:
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [255]:
df.to_csv('cafe3.csv',index=False)

In [256]:
df=pd.read_csv('cafe3.csv')

In [257]:
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [258]:
df.replace('아메리카노','룽고',inplace=True)
df.replace('녹차','그린티',inplace=True)
df

      메뉴    가격  칼로리    원산지
0     룽고  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6    그린티  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [260]:
change={'룽고':'아메리카노','그린티':'녹차'}
df.replace(change,inplace=True)
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [261]:
df.loc[6,'원산지']='대한민국'

In [262]:
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0   대한민국
7   딴짓커피  2000   20  코스타리카

In [263]:
df.loc[1:2,'이벤트가']=1000

In [264]:
df

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0
3   카푸치노  5000  110   과테말라     NaN
4  에스프레소  4000   20  코스타리카     NaN
5    밀크티  5900  210  코스타리카     NaN
6     녹차  5300    0   대한민국     NaN
7   딴짓커피  2000   20  코스타리카     NaN

In [265]:
df.to_csv('cafe4.csv',index=False)

In [266]:
import pandas as pd

In [267]:
df=pd.DataFrame({'A':['데이터분석','기본 학습서','퇴근 후 열공'],
                 'B':[10,20,30],
                 'C':['ab cd','AB CD','ab cd']})

In [268]:
df

         A   B      C
0    데이터분석  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [269]:
df['A']=df['A'].str.replace('분석','시각화')

In [270]:
df

         A   B      C
0   데이터시각화  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [272]:
df['B']=df['B'].replace(10,100)

In [273]:
df

         A    B      C
0   데이터시각화  100  ab cd
1   기본 학습서   20  AB CD
2  퇴근 후 열공   30  ab cd