<a href="https://colab.research.google.com/github/gumurytv/bigdataCert/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0_%EC%8B%A4%EA%B8%B0_PART1_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
menu=pd.Series(['비빔밥','김치찌개','된장찌개'])

In [3]:
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [4]:
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [5]:
price=pd.Series([10000,9000,8000])

In [6]:
price

0    10000
1     9000
2     8000
dtype: int64

In [7]:
df=pd.DataFrame({'메뉴':['비빔밥','김치찌개','된장찌개'],
                 '가격':[10000,9000,8000],
                 '원산지':['국내산','국내산','국내산']})

In [8]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [9]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [10]:
df[['메뉴']]

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [11]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [12]:
df[['메뉴','가격']]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [13]:
cols=['메뉴','가격']

In [14]:
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [15]:
type[df]

type[     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산]

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
print('df:',type(df))

df: <class 'pandas.core.frame.DataFrame'>

In [18]:
df=pd.DataFrame({
    '메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    '가격':[4500,5000,5500,5000,4000,5900,5300],
    '칼로리':[10,110,250,110,20,210,0]
})

In [19]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [20]:
df.to_csv('temp.csv')

In [21]:
temp_df=pd.read_csv('temp.csv')

In [22]:
temp_df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [23]:
df.to_csv('cafe.csv',index=False)

In [24]:
df=pd.read_csv('cafe.csv')

In [25]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [26]:
df.shape

(7, 3)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [28]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [29]:
df_car=pd.DataFrame({'car':['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
                  'size':['S','M','S','S','M','M','L','S','S','M','S']})

In [30]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [31]:
df_car

      car size
0   Sedan    S
1     SUV    M
2   Sedan    S
3     SUV    S
4     SUV    M
5     SUV    M
6   Sedan    L
7   Sedan    S
8   Sedan    S
9   Sedan    M
10  Sedan    S

In [32]:
df_car.head(3)

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S

In [33]:
df_car.nunique()

car     2
size    3
dtype: int64

In [34]:
print(df_car['car'].unique())

['Sedan' 'SUV']

In [35]:
print(df_car['size'].unique())

['S' 'M' 'L']

In [36]:
df_car['car'].value_counts()

car
Sedan    7
SUV      4
Name: count, dtype: int64

In [37]:
df.value_counts()

메뉴     가격    칼로리
녹차     5300  0      1
밀크티    5900  210    1
아메리카노  4500  10     1
에스프레소  4000  20     1
카페라떼   5000  110    1
카페모카   5500  250    1
카푸치노   5000  110    1
Name: count, dtype: int64

In [38]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [39]:
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [40]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [41]:
data={
    '메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    '가격':[4500,5000,5500,5000,4000,5900,5300],
    '칼로리':['10','110','250','110','20','210','0']
}

In [42]:
df=pd.DataFrame(data)

In [43]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [44]:
data

{'메뉴': ['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
 '가격': [4500, 5000, 5500, 5000, 4000, 5900, 5300],
 '칼로리': ['10', '110', '250', '110', '20', '210', '0']}

In [45]:
df['가격']=df['가격'].astype('int')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [47]:
df['칼로리']=df['칼로리'].astype('float')

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [49]:
df=pd.read_csv('cafe.csv')

In [50]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [51]:
df['new']=0

In [52]:
df.head()

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0
2   카페모카  5500  250    0
3   카푸치노  5000  110    0
4  에스프레소  4000   20    0

In [53]:
discount=0.2

In [54]:
df['할인가']=df['가격']*(1-discount)

In [55]:
df

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0
4  에스프레소  4000   20    0  3200.0
5    밀크티  5900  210    0  4720.0
6     녹차  5300    0    0  4240.0

In [56]:
df=pd.read_csv('cafe.csv')

In [57]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [58]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [59]:
df.drop(1,axis=0,inplace=True)

In [60]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [61]:
df=df.drop('메뉴',axis=1)

In [62]:
df

     가격  칼로리
0  4500   10
2  5500  250
3  5000  110
4  4000   20
5  5900  210
6  5300    0

In [63]:
df=pd.read_csv('cafe.csv')

In [64]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [65]:
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [66]:
df.loc[1,'가격']

np.int64(5000)

In [67]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [68]:
df.loc[2,'메뉴':'칼로리']

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [69]:
df.loc[2,['메뉴','칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [70]:
df.loc[1:3,['메뉴','칼로리']]

     메뉴  칼로리
1  카페라떼  110
2  카페모카  250
3  카푸치노  110

In [71]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [72]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [73]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [74]:
df.to_csv('cafe.csv')

In [75]:
df=pd.read_csv('cafe.csv')

In [76]:
df

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [77]:
df.head(2)

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110

In [78]:
df.loc[0]

Unnamed: 0        0
메뉴            아메리카노
가격             4500
칼로리              10
Name: 0, dtype: object

In [79]:
df.loc[1]

Unnamed: 0       1
메뉴            카페라떼
가격            5000
칼로리            110
Name: 1, dtype: object

In [80]:
df.loc[0,'가격']

np.int64(4500)

In [81]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [82]:
df.loc[0:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [83]:
df.loc[1:,'가격']

1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [84]:
 df.loc[2,'메뉴':'칼로리']

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [85]:
df.loc[2,['메뉴','칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [86]:
df

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [87]:
df.drop(0,axis=0,inplace=True)

In [88]:
df

   Unnamed: 0     메뉴    가격  칼로리
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [89]:
df.iloc[0]

Unnamed: 0       1
메뉴            카페라떼
가격            5000
칼로리            110
Name: 1, dtype: object

In [90]:
df.iloc[1:3]

   Unnamed: 0    메뉴    가격  칼로리
2           2  카페모카  5500  250
3           3  카푸치노  5000  110

In [91]:
df.head()

   Unnamed: 0     메뉴    가격  칼로리
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210

In [92]:
df.iloc[1:4]

   Unnamed: 0     메뉴    가격  칼로리
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [93]:
df.loc[2:4,'메뉴':'칼로리']

      메뉴    가격  칼로리
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [94]:
df.head(2)

   Unnamed: 0    메뉴    가격  칼로리
1           1  카페라떼  5000  110
2           2  카페모카  5500  250

In [95]:
import numpy as np

In [96]:
df['원산지']=np.nan

In [97]:
df

   Unnamed: 0     메뉴    가격  칼로리  원산지
1           1   카페라떼  5000  110  NaN
2           2   카페모카  5500  250  NaN
3           3   카푸치노  5000  110  NaN
4           4  에스프레소  4000   20  NaN
5           5    밀크티  5900  210  NaN
6           6     녹차  5300    0  NaN

In [98]:
df

   Unnamed: 0     메뉴    가격  칼로리  원산지
1           1   카페라떼  5000  110  NaN
2           2   카페모카  5500  250  NaN
3           3   카푸치노  5000  110  NaN
4           4  에스프레소  4000   20  NaN
5           5    밀크티  5900  210  NaN
6           6     녹차  5300    0  NaN

In [99]:
df.loc[1,'원산지']='콜롬비아'

/tmp/ipykernel_7745/3595826506.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[1,'원산지']='콜롬비아'

In [100]:
df

   Unnamed: 0     메뉴    가격  칼로리   원산지
1           1   카페라떼  5000  110  콜롬비아
2           2   카페모카  5500  250   NaN
3           3   카푸치노  5000  110   NaN
4           4  에스프레소  4000   20   NaN
5           5    밀크티  5900  210   NaN
6           6     녹차  5300    0   NaN

In [101]:
df.loc[2:6,'원산지']='과테말라'

In [102]:
df

   Unnamed: 0     메뉴    가격  칼로리   원산지
1           1   카페라떼  5000  110  콜롬비아
2           2   카페모카  5500  250  과테말라
3           3   카푸치노  5000  110  과테말라
4           4  에스프레소  4000   20  과테말라
5           5    밀크티  5900  210  과테말라
6           6     녹차  5300    0  과테말라

In [103]:
df.loc['시즌']=['크리스마스라떼',1,6000,300,'한국']

In [104]:
df

   Unnamed: 0     메뉴    가격  칼로리   원산지
1           1   카페라떼  5000  110  콜롬비아
2           2   카페모카  5500  250  과테말라
3           3   카푸치노  5000  110  과테말라
4           4  에스프레소  4000   20  과테말라
5           5    밀크티  5900  210  과테말라
6           6     녹차  5300    0  과테말라
시즌    크리스마스라떼      1  6000  300    한국

In [105]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [106]:
df

       메뉴    가격  칼로리   원산지
1    카페라떼  5000  110  콜롬비아
2    카페모카  5500  250  과테말라
3    카푸치노  5000  110  과테말라
4   에스프레소  4000   20  과테말라
5     밀크티  5900  210  과테말라
6      녹차  5300    0  과테말라
시즌      1  6000  300    한국

In [107]:
df.loc[7]={'메뉴':'딴짓커피','가격':'3000','칼로리':'1100'}

In [108]:
df

       메뉴    가격   칼로리   원산지
1    카페라떼  5000   110  콜롬비아
2    카페모카  5500   250  과테말라
3    카푸치노  5000   110  과테말라
4   에스프레소  4000    20  과테말라
5     밀크티  5900   210  과테말라
6      녹차  5300     0  과테말라
시즌      1  6000   300    한국
7    딴짓커피  3000  1100   NaN

In [109]:
df.drop('시즌',axis=0,inplace=True)

In [110]:
df

      메뉴    가격   칼로리   원산지
1   카페라떼  5000   110  콜롬비아
2   카페모카  5500   250  과테말라
3   카푸치노  5000   110  과테말라
4  에스프레소  4000    20  과테말라
5    밀크티  5900   210  과테말라
6     녹차  5300     0  과테말라
7   딴짓커피  3000  1100   NaN

In [111]:
df.to_csv('cafe2.csv',index=False)

In [112]:
df=pd.read_csv('cafe2.csv')

In [113]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [114]:
df.sort_index(ascending=False)

      메뉴    가격   칼로리   원산지
6   딴짓커피  3000  1100   NaN
5     녹차  5300     0  과테말라
4    밀크티  5900   210  과테말라
3  에스프레소  4000    20  과테말라
2   카푸치노  5000   110  과테말라
1   카페모카  5500   250  과테말라
0   카페라떼  5000   110  콜롬비아

In [115]:
df.sort_values('가격',ascending=False)

      메뉴    가격   칼로리   원산지
4    밀크티  5900   210  과테말라
1   카페모카  5500   250  과테말라
5     녹차  5300     0  과테말라
2   카푸치노  5000   110  과테말라
0   카페라떼  5000   110  콜롬비아
3  에스프레소  4000    20  과테말라
6   딴짓커피  3000  1100   NaN

In [116]:
df.sort_values(['가격','메뉴'],ascending=[False,True],inplace=True)

In [117]:
df

      메뉴    가격   칼로리   원산지
4    밀크티  5900   210  과테말라
1   카페모카  5500   250  과테말라
5     녹차  5300     0  과테말라
0   카페라떼  5000   110  콜롬비아
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
6   딴짓커피  3000  1100   NaN

In [118]:
df.reset_index(drop=True)

      메뉴    가격   칼로리   원산지
0    밀크티  5900   210  과테말라
1   카페모카  5500   250  과테말라
2     녹차  5300     0  과테말라
3   카페라떼  5000   110  콜롬비아
4   카푸치노  5000   110  과테말라
5  에스프레소  4000    20  과테말라
6   딴짓커피  3000  1100   NaN

In [119]:
df=pd.read_csv('cafe2.csv')

In [120]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [121]:
df['칼로리']<50

0    False
1    False
2    False
3     True
4    False
5     True
6    False
Name: 칼로리, dtype: bool

In [122]:
cond=df['칼로리']<50

In [123]:
df[cond]

      메뉴    가격  칼로리   원산지
3  에스프레소  4000   20  과테말라
5     녹차  5300    0  과테말라

In [124]:
df[~cond]

     메뉴    가격   칼로리   원산지
0  카페라떼  5000   110  콜롬비아
1  카페모카  5500   250  과테말라
2  카푸치노  5000   110  과테말라
4   밀크티  5900   210  과테말라
6  딴짓커피  3000  1100   NaN

In [125]:
cond1=df['가격']>=5000
cond2=df['칼로리']>100
df[cond1&cond2]

     메뉴    가격  칼로리   원산지
0  카페라떼  5000  110  콜롬비아
1  카페모카  5500  250  과테말라
2  카푸치노  5000  110  과테말라
4   밀크티  5900  210  과테말라

In [126]:
cond1=df['가격']>=5000
cond2=df['칼로리']>100
df[cond1|cond2]

     메뉴    가격   칼로리   원산지
0  카페라떼  5000   110  콜롬비아
1  카페모카  5500   250  과테말라
2  카푸치노  5000   110  과테말라
4   밀크티  5900   210  과테말라
5    녹차  5300     0  과테말라
6  딴짓커피  3000  1100   NaN

In [127]:
cond=df['원산지']=='과테말라'

In [128]:
df[cond]

      메뉴    가격  칼로리   원산지
1   카페모카  5500  250  과테말라
2   카푸치노  5000  110  과테말라
3  에스프레소  4000   20  과테말라
4    밀크티  5900  210  과테말라
5     녹차  5300    0  과테말라

In [129]:
cond2=df['가격']<=5000

In [130]:
df[cond&cond2]

      메뉴    가격  칼로리   원산지
2   카푸치노  5000  110  과테말라
3  에스프레소  4000   20  과테말라

In [131]:
cond=df['메뉴'].isin(['녹차'])

In [132]:
df[cond]

   메뉴    가격  칼로리   원산지
5  녹차  5300    0  과테말라

In [133]:
box=['녹차','카푸치노','카페라떼']

In [134]:
cond=df.isin(box)

In [135]:
df[cond]

     메뉴  가격  칼로리  원산지
0  카페라떼 NaN  NaN  NaN
1   NaN NaN  NaN  NaN
2  카푸치노 NaN  NaN  NaN
3   NaN NaN  NaN  NaN
4   NaN NaN  NaN  NaN
5    녹차 NaN  NaN  NaN
6   NaN NaN  NaN  NaN

In [136]:
df=pd.read_csv('cafe2.csv')

In [137]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [138]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False   True

In [139]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False   True

In [140]:
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    1
dtype: int64

In [141]:
df.isna().sum()

메뉴     0
가격     0
칼로리    0
원산지    1
dtype: int64

In [142]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [143]:
df['원산지'].fillna('코스타리카',inplace=True)

/tmp/ipykernel_7745/3660102855.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['원산지'].fillna('코스타리카',inplace=True)

In [144]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [145]:
df.to_csv('cafe3.csv',index=False)

In [146]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [147]:
df=pd.read_csv('cafe3.csv')

In [148]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [149]:
df.replace('아메리카노','룽고',inplace=True)

In [150]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [151]:
df.replace('녹차','그린티',inplace=True)

In [152]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5    그린티  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [153]:
change={'카페모카':'아메리카노','그린티':'녹차'}

In [154]:
df.replace(change,inplace=True)

In [155]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1  아메리카노  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [156]:
df.loc[5,'원산지']='대한민국'

In [157]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1  아메리카노  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   대한민국
6   딴짓커피  3000  1100  코스타리카

In [158]:
df.loc[1:2,'이벤트가']=1000

In [159]:
df

      메뉴    가격   칼로리    원산지    이벤트가
0   카페라떼  5000   110   콜롬비아     NaN
1  아메리카노  5500   250   과테말라  1000.0
2   카푸치노  5000   110   과테말라  1000.0
3  에스프레소  4000    20   과테말라     NaN
4    밀크티  5900   210   과테말라     NaN
5     녹차  5300     0   대한민국     NaN
6   딴짓커피  3000  1100  코스타리카     NaN

In [160]:
df.to_csv('cafe4.csv')

In [161]:
import pandas as pd

In [162]:
df=pd.DataFrame({'A':['데이터 분석','기본 학습서','퇴근 후 열공'],
                 'B':[10,20,30],
                 'C':['ab cd','AB CD','ab cd ']})

In [163]:
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [164]:
df.replace('분석','시각화')

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [165]:
df['A']=df['A'].str.replace('분석','시각화')

In [166]:
df

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [167]:
df['B']=df['B'].replace(10,100)

In [168]:
df

         A    B       C
0  데이터 시각화  100   ab cd
1   기본 학습서   20   AB CD
2  퇴근 후 열공   30  ab cd

In [ ]:
df['A'].str.split()

In [ ]:
df['A'].str.split()[2]

In [ ]:
df['D']=df['A'].str.split().str[0]

In [ ]:
df

In [ ]:
df['A'].str.contains('기본')

In [ ]:
df['기본포함여부']=df['A'].str.contains('기본')

In [ ]:
df

In [ ]:
df

In [ ]:
df['문자길이']=df['A'].str.len()

In [ ]:
df

In [ ]:
'AB cd'=='ab CD'

In [ ]:
df

In [ ]:
df['C']=df['C'].str.lower()

In [ ]:
df

In [ ]:
df['C']=df['C'].str.upper()

In [ ]:
df

In [ ]:
df['C']=='AB CD'

In [ ]:
df['C']=df['C'].str.lower()
df['C']=df['C'].str.replace(" ","")

In [ ]:
df

In [ ]:
df['C'].str[1:3]

In [ ]:
df['C'].str[2:3]

In [ ]:
df['C'][1:2]

In [ ]:
import pandas as pd
df=pd.read_csv('cafe4.csv')

In [ ]:
df

In [ ]:
df['메뉴'].str.len()

In [ ]:
print(len(df))

In [ ]:
df.shape

In [ ]:
cond=df['가격']>5000

In [ ]:
cond

In [ ]:
sum(cond)

In [ ]:
len(df[cond])

In [ ]:
df.sum(numeric_only=True)

In [ ]:
df

In [ ]:
df=df.T

In [ ]:
df

In [ ]:
df.sum(axis=1,numeric_only=True)

In [ ]:
df=pd.read_csv('cafe4.csv')

In [ ]:
df

In [ ]:
df.sum(axis=1,numeric_only=True)

In [ ]:
df

In [ ]:
df=pd.read_csv('cafe4.csv')

In [ ]:
df

In [ ]:
df.to_csv('cafe4.csv',index=None)

In [ ]:
df=pd.read_csv('cafe4.csv',index_col=0)

In [ ]:
df

In [ ]:
cond=df['가격'].quantile(.25)>df['가격']

In [ ]:
df[cond]

In [ ]:
cond=df['가격']>df['가격'].quantile(.75)

In [ ]:
df[cond]

In [ ]:
df['원산지'].mode()[0]

In [ ]:
df['가격'].idxmax()

In [ ]:
df['가격'].idxmin()

In [ ]:
max_ind=df['가격'].idxmax()

In [ ]:
max_ind

In [ ]:
df.loc[max_ind]['메뉴']

In [ ]:
df.nlargest(3,'가격')

In [ ]:
df.nsmallest(3,'가격')

In [ ]:
df.sort_values('가격',ascending=False).head(3)

In [ ]:
def cal(x):
  if x>=100:
    return "No"
  else:
    return "Yes"

In [ ]:
df['먹어도 될까요']=df['칼로리'].apply(cal)

In [ ]:
df

In [ ]:
import pandas as pd
df=pd.DataFrame({'Name':{0:'쿼카',1:'알파카',2:'시바견'},
                 '수학':{0:90,1:93,2:85},
                 '영어':{0:92,1:84,2:86},
                 '국어':{0:91,1:94,2:83}})

In [ ]:
df

In [ ]:
pd.melt(df,id_vars=['Name'])

In [ ]:
pd.melt(df,id_vars=['Name'],value_vars=['수학','영어'],var_name='과목',value_name='점수')

In [ ]:
import pandas as pd
df=pd.DataFrame({'반':{0:'A반',1:'B반',2:'C반'},
                '이름':{0:'쿼카',1:'알파카',2:'시바견'},
                 '수학':{0:90,1:93,2:85},
                 '영어':{0:92,1:84,2:86},
                 '국어':{0:91,1:94,2:83}})

In [ ]:
df

In [ ]:
pd.melt(df,id_vars=['반','이름'],value_vars=['수학','영어'],var_name='과목',value_name='점수')

In [172]:
df=pd.read_csv('cafe4.csv',index_col=0)

In [173]:
df

      메뉴    가격   칼로리    원산지    이벤트가
0   카페라떼  5000   110   콜롬비아     NaN
1  아메리카노  5500   250   과테말라  1000.0
2   카푸치노  5000   110   과테말라  1000.0
3  에스프레소  4000    20   과테말라     NaN
4    밀크티  5900   210   과테말라     NaN
5     녹차  5300     0   대한민국     NaN
6   딴짓커피  3000  1100  코스타리카     NaN

In [177]:
df.groupby(['원산지','칼로리']).mean(numeric_only=True)

                가격    이벤트가
원산지   칼로리
과테말라  20    4000.0     NaN
      110   5000.0  1000.0
      210   5900.0     NaN
      250   5500.0  1000.0
대한민국  0     5300.0     NaN
코스타리카 1100  3000.0     NaN
콜롬비아  110   5000.0     NaN

In [179]:
import pandas as pd
import numpy as np

In [184]:
df.groupby(['원산지','칼로리'])[['가격', '이벤트가']].agg(['mean','sum'])

                가격          이벤트가
              mean   sum    mean     sum
원산지   칼로리
과테말라  20    4000.0  4000     NaN     0.0
      110   5000.0  5000  1000.0  1000.0
      210   5900.0  5900     NaN     0.0
      250   5500.0  5500  1000.0  1000.0
대한민국  0     5300.0  5300     NaN     0.0
코스타리카 1100  3000.0  3000     NaN     0.0
콜롬비아  110   5000.0  5000     NaN     0.0

In [188]:
df.groupby(['원산지','칼로리'])[['가격','이벤트가']].agg(['mean','sum'])

                가격          이벤트가
              mean   sum    mean     sum
원산지   칼로리
과테말라  20    4000.0  4000     NaN     0.0
      110   5000.0  5000  1000.0  1000.0
      210   5900.0  5900     NaN     0.0
      250   5500.0  5500  1000.0  1000.0
대한민국  0     5300.0  5300     NaN     0.0
코스타리카 1100  3000.0  3000     NaN     0.0
콜롬비아  110   5000.0  5000     NaN     0.0

In [192]:
df.groupby(['원산지','칼로리']).mean(numeric_only=True).reset_index()

     원산지   칼로리      가격    이벤트가
0   과테말라    20  4000.0     NaN
1   과테말라   110  5000.0  1000.0
2   과테말라   210  5900.0     NaN
3   과테말라   250  5500.0  1000.0
4   대한민국     0  5300.0     NaN
5  코스타리카  1100  3000.0     NaN
6   콜롬비아   110  5000.0     NaN

      메뉴    가격   칼로리    원산지    이벤트가
0   카페라떼  5000   110   콜롬비아     NaN
1  아메리카노  5500   250   과테말라  1000.0
2   카푸치노  5000   110   과테말라  1000.0
3  에스프레소  4000    20   과테말라     NaN
4    밀크티  5900   210   과테말라     NaN
5     녹차  5300     0   대한민국     NaN
6   딴짓커피  3000  1100  코스타리카     NaN

In [193]:
import pandas as pd

In [194]:
df=pd.DataFrame({'과일':['딸기','블루베리','딸기','블루베리','딸기','블루베리','딸기','블루베리'],
                 '가격':[1000,None,1500,None,2000,2500,None,1800]})

In [195]:
df

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [197]:
price=df.groupby('과일')['가격'].transform('mean')

In [198]:
price

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: 가격, dtype: float64

In [199]:
df['가격']=df['가격'].fillna(price)

In [200]:
df

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [201]:
df=pd.DataFrame({'과일':['딸기','블루베리','딸기','블루베리','딸기','블루베리','딸기','블루베리'],
                 '등급':['B','B','A','A','A','A','B','B'],
                 '가격':[1000,None,1500,None,2000,2500,None,1800],
                 })

In [202]:
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B     NaN
2    딸기  A  1500.0
3  블루베리  A     NaN
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B     NaN
7  블루베리  B  1800.0

In [203]:
price=df.groupby(['과일','등급'])['가격'].transform('mean')

In [204]:
price

0    1000.0
1    1800.0
2    1750.0
3    2500.0
4    1750.0
5    2500.0
6    1000.0
7    1800.0
Name: 가격, dtype: float64

In [205]:
df['가격']=df['가격'].fillna(price)

In [206]:
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B  1800.0
2    딸기  A  1500.0
3  블루베리  A  2500.0
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B  1000.0
7  블루베리  B  1800.0

In [207]:
import pandas as pd

In [208]:
df=pd.DataFrame({'커피종류':['아메리카노','아메리카노','아메리카노','라떼','라떼','라떼'],
                 '컵크기':['Small','Medium','Large','Small','Medium','Large'],
                 '판매량':[120,150,200,100,130,180]})

In [210]:
df

    커피종류     컵크기  판매량
0  아메리카노   Small  120
1  아메리카노  Medium  150
2  아메리카노   Large  200
3     라떼   Small  100
4     라떼  Medium  130
5     라떼   Large  180

In [212]:
grouped=df.groupby(['커피종류','컵크기'])['판매량'].sum()

In [213]:
grouped

커피종류   컵크기
라떼     Large     180
       Medium    130
       Small     100
아메리카노  Large     200
       Medium    150
       Small     120
Name: 판매량, dtype: int64

In [216]:
grouped.unstack().unstack()

컵크기     커피종류
Large   라떼       180
        아메리카노    200
Medium  라떼       130
        아메리카노    150
Small   라떼       100
        아메리카노    120
dtype: int64

In [217]:
import pandas as pd
data={'Data1':['2024-02-17','2024-02-18','2024-02-19','2024-02-20'],
      'Data2':['2024:02:17','2024:02:18','2024:02:19','2024:02:20'],
      'Data3':['24/02/17','24/02/18','24/02/19','24/02/20'],
      'Data4':['02/17/2024','02/18/2024','02/19/2024','02/20/2024'],
      'Data5':['17-Feb-2024','18-Feb-2024','19-Feb-2024','20-Feb-2024'],
      'DateTime1':['2024-02-17 13:50:30','2024-02-18 14:55:45','2024-02-19 03:30:15','2024-02-20 16:10:50'],
      'DataTime2':['2024-02-17','2024-02-18','2024-02-19','2024-02-20'],
      'DataTime3':['2024-02-17','2024-02-18','2024-02-19','2024-02-20'],
      'DataTime4':['2024-02-17','2024-02-18','2024-02-19','2024-02-20']}

In [218]:
data

{'Data1': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
 'Data2': ['2024:02:17', '2024:02:18', '2024:02:19', '2024:02:20'],
 'Data3': ['24/02/17', '24/02/18', '24/02/19', '24/02/20'],
 'Data4': ['02/17/2024', '02/18/2024', '02/19/2024', '02/20/2024'],
 'Data5': ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024', '20-Feb-2024'],
 'DateTime1': ['2024-02-17 13:50:30',
  '2024-02-18 14:55:45',
  '2024-02-19 03:30:15',
  '2024-02-20 16:10:50'],
 'DataTime2': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
 'DataTime3': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
 'DataTime4': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20']}

In [219]:
df.DataFrame(data)

AttributeError: 'DataFrame' object has no attribute 'DataFrame'

In [221]:
df=pd.DataFrame(data)

In [222]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20

In [223]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data1      4 non-null      object
 1   Data2      4 non-null      object
 2   Data3      4 non-null      object
 3   Data4      4 non-null      object
 4   Data5      4 non-null      object
 5   DateTime1  4 non-null      object
 6   DataTime2  4 non-null      object
 7   DataTime3  4 non-null      object
 8   DataTime4  4 non-null      object
dtypes: object(9)
memory usage: 420.0+ bytes

In [224]:
df.to_csv('date_data.csv',index=False)

In [225]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20

In [226]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20

In [229]:
df=pd.read_csv('date_data.csv')

In [230]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20

In [237]:
df['Data1']=pd.to_datetime(df['Data1'])
df['Data2']=pd.to_datetime(df['Data2'],format='%Y:%m:%d')
df['Data3']=pd.to_datetime(df['Data3'])
df['Data3']=pd.to_datetime(df['Data3'])
df['Data4']=pd.to_datetime(df['Data4'])
df['Data5']=pd.to_datetime(df['Data5'])
df['DateTime1']=pd.to_datetime(df['DateTime1'])
df['DataTime2']=pd.to_datetime(df['DataTime2'])
df['DataTime3']=pd.to_datetime(df['DataTime3'])
df['DataTime4']=pd.to_datetime(df['DataTime4'])

/tmp/ipykernel_7745/873710502.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Data3']=pd.to_datetime(df['Data3'])

In [238]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data1      4 non-null      datetime64[ns]
 1   Data2      4 non-null      datetime64[ns]
 2   Data3      4 non-null      datetime64[ns]
 3   Data4      4 non-null      datetime64[ns]
 4   Data5      4 non-null      datetime64[ns]
 5   DateTime1  4 non-null      datetime64[ns]
 6   DataTime2  4 non-null      datetime64[ns]
 7   DataTime3  4 non-null      datetime64[ns]
 8   DataTime4  4 non-null      datetime64[ns]
dtypes: datetime64[ns](9)
memory usage: 420.0 bytes

In [240]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data1      4 non-null      datetime64[ns]
 1   Data2      4 non-null      datetime64[ns]
 2   Data3      4 non-null      datetime64[ns]
 3   Data4      4 non-null      datetime64[ns]
 4   Data5      4 non-null      datetime64[ns]
 5   DateTime1  4 non-null      datetime64[ns]
 6   DataTime2  4 non-null      datetime64[ns]
 7   DataTime3  4 non-null      datetime64[ns]
 8   DataTime4  4 non-null      datetime64[ns]
dtypes: datetime64[ns](9)
memory usage: 420.0 bytes

In [239]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024-02-17,2017-02-24,2024-02-17,2024-02-17,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024-02-18,2018-02-24,2024-02-18,2024-02-18,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024-02-19,2019-02-24,2024-02-19,2024-02-19,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024-02-20,2020-02-24,2024-02-20,2024-02-20,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20