<a href="https://colab.research.google.com/github/gumurytv/bigdataCert/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0_%EC%8B%A4%EA%B8%B0_PART1_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [299]:
import pandas as pd

In [300]:
menu=pd.Series(['비빔밥','김치찌개','된장찌개'])

In [301]:
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [302]:
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [303]:
price=pd.Series([10000,9000,8000])

In [304]:
price

0    10000
1     9000
2     8000
dtype: int64

In [305]:
df=pd.DataFrame({'메뉴':['비빔밥','김치찌개','된장찌개'],
                 '가격':[10000,9000,8000],
                 '원산지':['국내산','국내산','국내산']})

In [306]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [307]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [308]:
df[['메뉴']]

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [309]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [310]:
df[['메뉴','가격']]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [311]:
cols=['메뉴','가격']

In [312]:
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [313]:
type[df]

type[     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산]

In [314]:
type(df)

pandas.core.frame.DataFrame

In [315]:
print('df:',type(df))

df: <class 'pandas.core.frame.DataFrame'>

In [316]:
df=pd.DataFrame({
    '메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    '가격':[4500,5000,5500,5000,4000,5900,5300],
    '칼로리':[10,110,250,110,20,210,0]
})

In [317]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [318]:
df.to_csv('temp.csv')

In [319]:
temp_df=pd.read_csv('temp.csv')

In [320]:
temp_df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [321]:
df.to_csv('cafe.csv',index=False)

In [322]:
df=pd.read_csv('cafe.csv')

In [323]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [324]:
df.shape

(7, 3)

In [325]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [326]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [327]:
df_car=pd.DataFrame({'car':['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
                  'size':['S','M','S','S','M','M','L','S','S','M','S']})

In [328]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [329]:
df_car

      car size
0   Sedan    S
1     SUV    M
2   Sedan    S
3     SUV    S
4     SUV    M
5     SUV    M
6   Sedan    L
7   Sedan    S
8   Sedan    S
9   Sedan    M
10  Sedan    S

In [330]:
df_car.head(3)

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S

In [331]:
df_car.nunique()

car     2
size    3
dtype: int64

In [332]:
print(df_car['car'].unique())

['Sedan' 'SUV']

In [333]:
print(df_car['size'].unique())

['S' 'M' 'L']

In [334]:
df_car['car'].value_counts()

car
Sedan    7
SUV      4
Name: count, dtype: int64

In [335]:
df.value_counts()

메뉴     가격    칼로리
녹차     5300  0      1
밀크티    5900  210    1
아메리카노  4500  10     1
에스프레소  4000  20     1
카페라떼   5000  110    1
카페모카   5500  250    1
카푸치노   5000  110    1
Name: count, dtype: int64

In [336]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [337]:
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [338]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [339]:
data={
    '메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    '가격':[4500,5000,5500,5000,4000,5900,5300],
    '칼로리':['10','110','250','110','20','210','0']
}

In [340]:
df=pd.DataFrame(data)

In [341]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [342]:
data

{'메뉴': ['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
 '가격': [4500, 5000, 5500, 5000, 4000, 5900, 5300],
 '칼로리': ['10', '110', '250', '110', '20', '210', '0']}

In [343]:
df['가격']=df['가격'].astype('int')

In [344]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [345]:
df['칼로리']=df['칼로리'].astype('float')

In [346]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [347]:
df=pd.read_csv('cafe.csv')

In [348]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [349]:
df['new']=0

In [350]:
df.head()

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0
2   카페모카  5500  250    0
3   카푸치노  5000  110    0
4  에스프레소  4000   20    0

In [351]:
discount=0.2

In [352]:
df['할인가']=df['가격']*(1-discount)

In [353]:
df

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0
4  에스프레소  4000   20    0  3200.0
5    밀크티  5900  210    0  4720.0
6     녹차  5300    0    0  4240.0

In [354]:
df=pd.read_csv('cafe.csv')

In [355]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [356]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [357]:
df.drop(1,axis=0,inplace=True)

In [358]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [359]:
df=df.drop('메뉴',axis=1)

In [360]:
df

     가격  칼로리
0  4500   10
2  5500  250
3  5000  110
4  4000   20
5  5900  210
6  5300    0

In [361]:
df=pd.read_csv('cafe.csv')

In [362]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [363]:
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [364]:
df.loc[1,'가격']

np.int64(5000)

In [365]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [366]:
df.loc[2,'메뉴':'칼로리']

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [367]:
df.loc[2,['메뉴','칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [368]:
df.loc[1:3,['메뉴','칼로리']]

     메뉴  칼로리
1  카페라떼  110
2  카페모카  250
3  카푸치노  110

In [369]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [370]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [371]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [372]:
df.to_csv('cafe.csv')

In [373]:
df=pd.read_csv('cafe.csv')

In [374]:
df

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [375]:
df.head(2)

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110

In [376]:
df.loc[0]

Unnamed: 0        0
메뉴            아메리카노
가격             4500
칼로리              10
Name: 0, dtype: object

In [377]:
df.loc[1]

Unnamed: 0       1
메뉴            카페라떼
가격            5000
칼로리            110
Name: 1, dtype: object

In [378]:
df.loc[0,'가격']

np.int64(4500)

In [379]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [380]:
df.loc[0:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [381]:
df.loc[1:,'가격']

1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [382]:
 df.loc[2,'메뉴':'칼로리']

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [383]:
df.loc[2,['메뉴','칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [384]:
df

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [385]:
df.drop(0,axis=0,inplace=True)

In [386]:
df

   Unnamed: 0     메뉴    가격  칼로리
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [387]:
df.iloc[0]

Unnamed: 0       1
메뉴            카페라떼
가격            5000
칼로리            110
Name: 1, dtype: object

In [388]:
df.iloc[1:3]

   Unnamed: 0    메뉴    가격  칼로리
2           2  카페모카  5500  250
3           3  카푸치노  5000  110

In [389]:
df.head()

   Unnamed: 0     메뉴    가격  칼로리
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210

In [390]:
df.iloc[1:4]

   Unnamed: 0     메뉴    가격  칼로리
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [391]:
df.loc[2:4,'메뉴':'칼로리']

      메뉴    가격  칼로리
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [392]:
df.head(2)

   Unnamed: 0    메뉴    가격  칼로리
1           1  카페라떼  5000  110
2           2  카페모카  5500  250

In [393]:
import numpy as np

In [394]:
df['원산지']=np.nan

In [395]:
df

   Unnamed: 0     메뉴    가격  칼로리  원산지
1           1   카페라떼  5000  110  NaN
2           2   카페모카  5500  250  NaN
3           3   카푸치노  5000  110  NaN
4           4  에스프레소  4000   20  NaN
5           5    밀크티  5900  210  NaN
6           6     녹차  5300    0  NaN

In [396]:
df

   Unnamed: 0     메뉴    가격  칼로리  원산지
1           1   카페라떼  5000  110  NaN
2           2   카페모카  5500  250  NaN
3           3   카푸치노  5000  110  NaN
4           4  에스프레소  4000   20  NaN
5           5    밀크티  5900  210  NaN
6           6     녹차  5300    0  NaN

In [397]:
df.loc[1,'원산지']='콜롬비아'

/tmp/ipykernel_11500/3595826506.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[1,'원산지']='콜롬비아'

In [398]:
df

   Unnamed: 0     메뉴    가격  칼로리   원산지
1           1   카페라떼  5000  110  콜롬비아
2           2   카페모카  5500  250   NaN
3           3   카푸치노  5000  110   NaN
4           4  에스프레소  4000   20   NaN
5           5    밀크티  5900  210   NaN
6           6     녹차  5300    0   NaN

In [399]:
df.loc[2:6,'원산지']='과테말라'

In [400]:
df

   Unnamed: 0     메뉴    가격  칼로리   원산지
1           1   카페라떼  5000  110  콜롬비아
2           2   카페모카  5500  250  과테말라
3           3   카푸치노  5000  110  과테말라
4           4  에스프레소  4000   20  과테말라
5           5    밀크티  5900  210  과테말라
6           6     녹차  5300    0  과테말라

In [401]:
df.loc['시즌']=['크리스마스라떼',1,6000,300,'한국']

In [402]:
df

   Unnamed: 0     메뉴    가격  칼로리   원산지
1           1   카페라떼  5000  110  콜롬비아
2           2   카페모카  5500  250  과테말라
3           3   카푸치노  5000  110  과테말라
4           4  에스프레소  4000   20  과테말라
5           5    밀크티  5900  210  과테말라
6           6     녹차  5300    0  과테말라
시즌    크리스마스라떼      1  6000  300    한국

In [403]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [404]:
df

       메뉴    가격  칼로리   원산지
1    카페라떼  5000  110  콜롬비아
2    카페모카  5500  250  과테말라
3    카푸치노  5000  110  과테말라
4   에스프레소  4000   20  과테말라
5     밀크티  5900  210  과테말라
6      녹차  5300    0  과테말라
시즌      1  6000  300    한국

In [405]:
df.loc[7]={'메뉴':'딴짓커피','가격':'3000','칼로리':'1100'}

In [406]:
df

       메뉴    가격   칼로리   원산지
1    카페라떼  5000   110  콜롬비아
2    카페모카  5500   250  과테말라
3    카푸치노  5000   110  과테말라
4   에스프레소  4000    20  과테말라
5     밀크티  5900   210  과테말라
6      녹차  5300     0  과테말라
시즌      1  6000   300    한국
7    딴짓커피  3000  1100   NaN

In [407]:
df.drop('시즌',axis=0,inplace=True)

In [408]:
df

      메뉴    가격   칼로리   원산지
1   카페라떼  5000   110  콜롬비아
2   카페모카  5500   250  과테말라
3   카푸치노  5000   110  과테말라
4  에스프레소  4000    20  과테말라
5    밀크티  5900   210  과테말라
6     녹차  5300     0  과테말라
7   딴짓커피  3000  1100   NaN

In [409]:
df.to_csv('cafe2.csv',index=False)

In [410]:
df=pd.read_csv('cafe2.csv')

In [411]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [412]:
df.sort_index(ascending=False)

      메뉴    가격   칼로리   원산지
6   딴짓커피  3000  1100   NaN
5     녹차  5300     0  과테말라
4    밀크티  5900   210  과테말라
3  에스프레소  4000    20  과테말라
2   카푸치노  5000   110  과테말라
1   카페모카  5500   250  과테말라
0   카페라떼  5000   110  콜롬비아

In [413]:
df.sort_values('가격',ascending=False)

      메뉴    가격   칼로리   원산지
4    밀크티  5900   210  과테말라
1   카페모카  5500   250  과테말라
5     녹차  5300     0  과테말라
2   카푸치노  5000   110  과테말라
0   카페라떼  5000   110  콜롬비아
3  에스프레소  4000    20  과테말라
6   딴짓커피  3000  1100   NaN

In [414]:
df.sort_values(['가격','메뉴'],ascending=[False,True],inplace=True)

In [415]:
df

      메뉴    가격   칼로리   원산지
4    밀크티  5900   210  과테말라
1   카페모카  5500   250  과테말라
5     녹차  5300     0  과테말라
0   카페라떼  5000   110  콜롬비아
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
6   딴짓커피  3000  1100   NaN

In [416]:
df.reset_index(drop=True)

      메뉴    가격   칼로리   원산지
0    밀크티  5900   210  과테말라
1   카페모카  5500   250  과테말라
2     녹차  5300     0  과테말라
3   카페라떼  5000   110  콜롬비아
4   카푸치노  5000   110  과테말라
5  에스프레소  4000    20  과테말라
6   딴짓커피  3000  1100   NaN

In [417]:
df=pd.read_csv('cafe2.csv')

In [418]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [419]:
df['칼로리']<50

0    False
1    False
2    False
3     True
4    False
5     True
6    False
Name: 칼로리, dtype: bool

In [420]:
cond=df['칼로리']<50

In [421]:
df[cond]

      메뉴    가격  칼로리   원산지
3  에스프레소  4000   20  과테말라
5     녹차  5300    0  과테말라

In [422]:
df[~cond]

     메뉴    가격   칼로리   원산지
0  카페라떼  5000   110  콜롬비아
1  카페모카  5500   250  과테말라
2  카푸치노  5000   110  과테말라
4   밀크티  5900   210  과테말라
6  딴짓커피  3000  1100   NaN

In [423]:
cond1=df['가격']>=5000
cond2=df['칼로리']>100
df[cond1&cond2]

     메뉴    가격  칼로리   원산지
0  카페라떼  5000  110  콜롬비아
1  카페모카  5500  250  과테말라
2  카푸치노  5000  110  과테말라
4   밀크티  5900  210  과테말라

In [424]:
cond1=df['가격']>=5000
cond2=df['칼로리']>100
df[cond1|cond2]

     메뉴    가격   칼로리   원산지
0  카페라떼  5000   110  콜롬비아
1  카페모카  5500   250  과테말라
2  카푸치노  5000   110  과테말라
4   밀크티  5900   210  과테말라
5    녹차  5300     0  과테말라
6  딴짓커피  3000  1100   NaN

In [425]:
cond=df['원산지']=='과테말라'

In [426]:
df[cond]

      메뉴    가격  칼로리   원산지
1   카페모카  5500  250  과테말라
2   카푸치노  5000  110  과테말라
3  에스프레소  4000   20  과테말라
4    밀크티  5900  210  과테말라
5     녹차  5300    0  과테말라

In [427]:
cond2=df['가격']<=5000

In [428]:
df[cond&cond2]

      메뉴    가격  칼로리   원산지
2   카푸치노  5000  110  과테말라
3  에스프레소  4000   20  과테말라

In [429]:
cond=df['메뉴'].isin(['녹차'])

In [430]:
df[cond]

   메뉴    가격  칼로리   원산지
5  녹차  5300    0  과테말라

In [431]:
box=['녹차','카푸치노','카페라떼']

In [432]:
cond=df.isin(box)

In [433]:
df[cond]

     메뉴  가격  칼로리  원산지
0  카페라떼 NaN  NaN  NaN
1   NaN NaN  NaN  NaN
2  카푸치노 NaN  NaN  NaN
3   NaN NaN  NaN  NaN
4   NaN NaN  NaN  NaN
5    녹차 NaN  NaN  NaN
6   NaN NaN  NaN  NaN

In [434]:
df=pd.read_csv('cafe2.csv')

In [435]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [436]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False   True

In [437]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False   True

In [438]:
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    1
dtype: int64

In [439]:
df.isna().sum()

메뉴     0
가격     0
칼로리    0
원산지    1
dtype: int64

In [440]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [441]:
df['원산지'].fillna('코스타리카',inplace=True)

/tmp/ipykernel_11500/3660102855.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['원산지'].fillna('코스타리카',inplace=True)

In [442]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [443]:
df.to_csv('cafe3.csv',index=False)

In [444]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [445]:
df=pd.read_csv('cafe3.csv')

In [446]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [447]:
df.replace('아메리카노','룽고',inplace=True)

In [448]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [449]:
df.replace('녹차','그린티',inplace=True)

In [450]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5    그린티  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [451]:
change={'카페모카':'아메리카노','그린티':'녹차'}

In [452]:
df.replace(change,inplace=True)

In [453]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1  아메리카노  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [454]:
df.loc[5,'원산지']='대한민국'

In [455]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1  아메리카노  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   대한민국
6   딴짓커피  3000  1100  코스타리카

In [456]:
df.loc[1:2,'이벤트가']=1000

In [457]:
df

      메뉴    가격   칼로리    원산지    이벤트가
0   카페라떼  5000   110   콜롬비아     NaN
1  아메리카노  5500   250   과테말라  1000.0
2   카푸치노  5000   110   과테말라  1000.0
3  에스프레소  4000    20   과테말라     NaN
4    밀크티  5900   210   과테말라     NaN
5     녹차  5300     0   대한민국     NaN
6   딴짓커피  3000  1100  코스타리카     NaN

In [458]:
df.to_csv('cafe4.csv')

In [459]:
import pandas as pd

In [460]:
df=pd.DataFrame({'A':['데이터 분석','기본 학습서','퇴근 후 열공'],
                 'B':[10,20,30],
                 'C':['ab cd','AB CD','ab cd ']})

In [461]:
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [462]:
df.replace('분석','시각화')

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [463]:
df['A']=df['A'].str.replace('분석','시각화')

In [464]:
df

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [465]:
df['B']=df['B'].replace(10,100)

In [466]:
df

         A    B       C
0  데이터 시각화  100   ab cd
1   기본 학습서   20   AB CD
2  퇴근 후 열공   30  ab cd

In [467]:
df['A'].str.split()

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [468]:
df['A'].str.split()[2]

['퇴근', '후', '열공']

In [469]:
df['D']=df['A'].str.split().str[0]

In [470]:
df

         A    B       C    D
0  데이터 시각화  100   ab cd  데이터
1   기본 학습서   20   AB CD   기본
2  퇴근 후 열공   30  ab cd    퇴근

In [471]:
df['A'].str.contains('기본')

0    False
1     True
2    False
Name: A, dtype: bool

In [472]:
df['기본포함여부']=df['A'].str.contains('기본')

In [473]:
df

         A    B       C    D  기본포함여부
0  데이터 시각화  100   ab cd  데이터   False
1   기본 학습서   20   AB CD   기본    True
2  퇴근 후 열공   30  ab cd    퇴근   False

In [474]:
df

         A    B       C    D  기본포함여부
0  데이터 시각화  100   ab cd  데이터   False
1   기본 학습서   20   AB CD   기본    True
2  퇴근 후 열공   30  ab cd    퇴근   False

In [475]:
df['문자길이']=df['A'].str.len()

In [476]:
df

         A    B       C    D  기본포함여부  문자길이
0  데이터 시각화  100   ab cd  데이터   False     7
1   기본 학습서   20   AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd    퇴근   False     7

In [477]:
'AB cd'=='ab CD'

False

In [478]:
df

         A    B       C    D  기본포함여부  문자길이
0  데이터 시각화  100   ab cd  데이터   False     7
1   기본 학습서   20   AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd    퇴근   False     7

In [479]:
df['C']=df['C'].str.lower()

In [480]:
df

         A    B       C    D  기본포함여부  문자길이
0  데이터 시각화  100   ab cd  데이터   False     7
1   기본 학습서   20   ab cd   기본    True     6
2  퇴근 후 열공   30  ab cd    퇴근   False     7

In [481]:
df['C']=df['C'].str.upper()

In [482]:
df

         A    B       C    D  기본포함여부  문자길이
0  데이터 시각화  100   AB CD  데이터   False     7
1   기본 학습서   20   AB CD   기본    True     6
2  퇴근 후 열공   30  AB CD    퇴근   False     7

In [483]:
df['C']=='AB CD'

0     True
1     True
2    False
Name: C, dtype: bool

In [484]:
df['C']=df['C'].str.lower()
df['C']=df['C'].str.replace(" ","")

In [485]:
df

         A    B     C    D  기본포함여부  문자길이
0  데이터 시각화  100  abcd  데이터   False     7
1   기본 학습서   20  abcd   기본    True     6
2  퇴근 후 열공   30  abcd   퇴근   False     7

In [486]:
df['C'].str[1:3]

0    bc
1    bc
2    bc
Name: C, dtype: object

In [487]:
df['C'].str[2:3]

0    c
1    c
2    c
Name: C, dtype: object

In [488]:
df['C'][1:2]

1    abcd
Name: C, dtype: object

In [489]:
import pandas as pd
df=pd.read_csv('cafe4.csv')

In [490]:
df

   Unnamed: 0     메뉴    가격   칼로리    원산지    이벤트가
0           0   카페라떼  5000   110   콜롬비아     NaN
1           1  아메리카노  5500   250   과테말라  1000.0
2           2   카푸치노  5000   110   과테말라  1000.0
3           3  에스프레소  4000    20   과테말라     NaN
4           4    밀크티  5900   210   과테말라     NaN
5           5     녹차  5300     0   대한민국     NaN
6           6   딴짓커피  3000  1100  코스타리카     NaN

In [491]:
df['메뉴'].str.len()

0    4
1    5
2    4
3    5
4    3
5    2
6    4
Name: 메뉴, dtype: int64

In [492]:
print(len(df))

7

In [493]:
df.shape

(7, 6)

In [494]:
cond=df['가격']>5000

In [495]:
cond

0    False
1     True
2    False
3    False
4     True
5     True
6    False
Name: 가격, dtype: bool

In [496]:
sum(cond)

3

In [497]:
len(df[cond])

3

In [498]:
df.sum(numeric_only=True)

Unnamed: 0       21.0
가격            33700.0
칼로리            1800.0
이벤트가           2000.0
dtype: float64

In [499]:
df

   Unnamed: 0     메뉴    가격   칼로리    원산지    이벤트가
0           0   카페라떼  5000   110   콜롬비아     NaN
1           1  아메리카노  5500   250   과테말라  1000.0
2           2   카푸치노  5000   110   과테말라  1000.0
3           3  에스프레소  4000    20   과테말라     NaN
4           4    밀크티  5900   210   과테말라     NaN
5           5     녹차  5300     0   대한민국     NaN
6           6   딴짓커피  3000  1100  코스타리카     NaN

In [500]:
df=df.T

In [501]:
df

               0       1       2      3     4     5      6
Unnamed: 0     0       1       2      3     4     5      6
메뉴          카페라떼   아메리카노    카푸치노  에스프레소   밀크티    녹차   딴짓커피
가격          5000    5500    5000   4000  5900  5300   3000
칼로리          110     250     110     20   210     0   1100
원산지         콜롬비아    과테말라    과테말라   과테말라  과테말라  대한민국  코스타리카
이벤트가         NaN  1000.0  1000.0    NaN   NaN   NaN    NaN

In [502]:
df.sum(axis=1,numeric_only=True)

Unnamed: 0    0.0
메뉴            0.0
가격            0.0
칼로리           0.0
원산지           0.0
이벤트가          0.0
dtype: float64

In [503]:
df=pd.read_csv('cafe4.csv')

In [504]:
df

   Unnamed: 0     메뉴    가격   칼로리    원산지    이벤트가
0           0   카페라떼  5000   110   콜롬비아     NaN
1           1  아메리카노  5500   250   과테말라  1000.0
2           2   카푸치노  5000   110   과테말라  1000.0
3           3  에스프레소  4000    20   과테말라     NaN
4           4    밀크티  5900   210   과테말라     NaN
5           5     녹차  5300     0   대한민국     NaN
6           6   딴짓커피  3000  1100  코스타리카     NaN

In [505]:
df.sum(axis=1,numeric_only=True)

0    5110.0
1    6751.0
2    6112.0
3    4023.0
4    6114.0
5    5305.0
6    4106.0
dtype: float64

In [506]:
df

   Unnamed: 0     메뉴    가격   칼로리    원산지    이벤트가
0           0   카페라떼  5000   110   콜롬비아     NaN
1           1  아메리카노  5500   250   과테말라  1000.0
2           2   카푸치노  5000   110   과테말라  1000.0
3           3  에스프레소  4000    20   과테말라     NaN
4           4    밀크티  5900   210   과테말라     NaN
5           5     녹차  5300     0   대한민국     NaN
6           6   딴짓커피  3000  1100  코스타리카     NaN

In [507]:
df=pd.read_csv('cafe4.csv')

In [508]:
df

   Unnamed: 0     메뉴    가격   칼로리    원산지    이벤트가
0           0   카페라떼  5000   110   콜롬비아     NaN
1           1  아메리카노  5500   250   과테말라  1000.0
2           2   카푸치노  5000   110   과테말라  1000.0
3           3  에스프레소  4000    20   과테말라     NaN
4           4    밀크티  5900   210   과테말라     NaN
5           5     녹차  5300     0   대한민국     NaN
6           6   딴짓커피  3000  1100  코스타리카     NaN

In [509]:
df.to_csv('cafe4.csv',index=None)

In [510]:
df=pd.read_csv('cafe4.csv',index_col=0)

In [511]:
df

               메뉴    가격   칼로리    원산지    이벤트가
Unnamed: 0
0            카페라떼  5000   110   콜롬비아     NaN
1           아메리카노  5500   250   과테말라  1000.0
2            카푸치노  5000   110   과테말라  1000.0
3           에스프레소  4000    20   과테말라     NaN
4             밀크티  5900   210   과테말라     NaN
5              녹차  5300     0   대한민국     NaN
6            딴짓커피  3000  1100  코스타리카     NaN

In [512]:
cond=df['가격'].quantile(.25)>df['가격']

In [513]:
df[cond]

               메뉴    가격   칼로리    원산지  이벤트가
Unnamed: 0
3           에스프레소  4000    20   과테말라   NaN
6            딴짓커피  3000  1100  코스타리카   NaN

In [514]:
cond=df['가격']>df['가격'].quantile(.75)

In [515]:
df[cond]

               메뉴    가격  칼로리   원산지    이벤트가
Unnamed: 0
1           아메리카노  5500  250  과테말라  1000.0
4             밀크티  5900  210  과테말라     NaN

In [516]:
df['원산지'].mode()[0]

'과테말라'

In [517]:
df['가격'].idxmax()

np.int64(4)

In [518]:
df['가격'].idxmin()

np.int64(6)

In [519]:
max_ind=df['가격'].idxmax()

In [520]:
max_ind

np.int64(4)

In [521]:
df.loc[max_ind]['메뉴']

'밀크티'

In [522]:
df.nlargest(3,'가격')

               메뉴    가격  칼로리   원산지    이벤트가
Unnamed: 0
4             밀크티  5900  210  과테말라     NaN
1           아메리카노  5500  250  과테말라  1000.0
5              녹차  5300    0  대한민국     NaN

In [523]:
df.nsmallest(3,'가격')

               메뉴    가격   칼로리    원산지  이벤트가
Unnamed: 0
6            딴짓커피  3000  1100  코스타리카   NaN
3           에스프레소  4000    20   과테말라   NaN
0            카페라떼  5000   110   콜롬비아   NaN

In [524]:
df.sort_values('가격',ascending=False).head(3)

               메뉴    가격  칼로리   원산지    이벤트가
Unnamed: 0
4             밀크티  5900  210  과테말라     NaN
1           아메리카노  5500  250  과테말라  1000.0
5              녹차  5300    0  대한민국     NaN

In [525]:
def cal(x):
  if x>=100:
    return "No"
  else:
    return "Yes"

In [526]:
df['먹어도 될까요']=df['칼로리'].apply(cal)

In [527]:
df

               메뉴    가격   칼로리    원산지    이벤트가 먹어도 될까요
Unnamed: 0
0            카페라떼  5000   110   콜롬비아     NaN      No
1           아메리카노  5500   250   과테말라  1000.0      No
2            카푸치노  5000   110   과테말라  1000.0      No
3           에스프레소  4000    20   과테말라     NaN     Yes
4             밀크티  5900   210   과테말라     NaN      No
5              녹차  5300     0   대한민국     NaN     Yes
6            딴짓커피  3000  1100  코스타리카     NaN      No

In [528]:
import pandas as pd
df=pd.DataFrame({'Name':{0:'쿼카',1:'알파카',2:'시바견'},
                 '수학':{0:90,1:93,2:85},
                 '영어':{0:92,1:84,2:86},
                 '국어':{0:91,1:94,2:83}})

In [529]:
df

  Name  수학  영어  국어
0   쿼카  90  92  91
1  알파카  93  84  94
2  시바견  85  86  83

In [530]:
pd.melt(df,id_vars=['Name'])

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86
6   쿼카       국어     91
7  알파카       국어     94
8  시바견       국어     83

In [531]:
pd.melt(df,id_vars=['Name'],value_vars=['수학','영어'],var_name='과목',value_name='점수')

  Name  과목  점수
0   쿼카  수학  90
1  알파카  수학  93
2  시바견  수학  85
3   쿼카  영어  92
4  알파카  영어  84
5  시바견  영어  86

In [532]:
import pandas as pd
df=pd.DataFrame({'반':{0:'A반',1:'B반',2:'C반'},
                '이름':{0:'쿼카',1:'알파카',2:'시바견'},
                 '수학':{0:90,1:93,2:85},
                 '영어':{0:92,1:84,2:86},
                 '국어':{0:91,1:94,2:83}})

In [533]:
df

    반   이름  수학  영어  국어
0  A반   쿼카  90  92  91
1  B반  알파카  93  84  94
2  C반  시바견  85  86  83

In [534]:
pd.melt(df,id_vars=['반','이름'],value_vars=['수학','영어'],var_name='과목',value_name='점수')

    반   이름  과목  점수
0  A반   쿼카  수학  90
1  B반  알파카  수학  93
2  C반  시바견  수학  85
3  A반   쿼카  영어  92
4  B반  알파카  영어  84
5  C반  시바견  영어  86

In [535]:
df=pd.read_csv('cafe4.csv',index_col=0)

In [536]:
df

               메뉴    가격   칼로리    원산지    이벤트가
Unnamed: 0
0            카페라떼  5000   110   콜롬비아     NaN
1           아메리카노  5500   250   과테말라  1000.0
2            카푸치노  5000   110   과테말라  1000.0
3           에스프레소  4000    20   과테말라     NaN
4             밀크티  5900   210   과테말라     NaN
5              녹차  5300     0   대한민국     NaN
6            딴짓커피  3000  1100  코스타리카     NaN

In [537]:
df.groupby(['원산지','칼로리']).mean(numeric_only=True)

                가격    이벤트가
원산지   칼로리
과테말라  20    4000.0     NaN
      110   5000.0  1000.0
      210   5900.0     NaN
      250   5500.0  1000.0
대한민국  0     5300.0     NaN
코스타리카 1100  3000.0     NaN
콜롬비아  110   5000.0     NaN

In [538]:
import pandas as pd
import numpy as np

In [539]:
df.groupby(['원산지','칼로리'])[['가격', '이벤트가']].agg(['mean','sum'])

                가격          이벤트가
              mean   sum    mean     sum
원산지   칼로리
과테말라  20    4000.0  4000     NaN     0.0
      110   5000.0  5000  1000.0  1000.0
      210   5900.0  5900     NaN     0.0
      250   5500.0  5500  1000.0  1000.0
대한민국  0     5300.0  5300     NaN     0.0
코스타리카 1100  3000.0  3000     NaN     0.0
콜롬비아  110   5000.0  5000     NaN     0.0

In [540]:
df.groupby(['원산지','칼로리'])[['가격','이벤트가']].agg(['mean','sum'])

                가격          이벤트가
              mean   sum    mean     sum
원산지   칼로리
과테말라  20    4000.0  4000     NaN     0.0
      110   5000.0  5000  1000.0  1000.0
      210   5900.0  5900     NaN     0.0
      250   5500.0  5500  1000.0  1000.0
대한민국  0     5300.0  5300     NaN     0.0
코스타리카 1100  3000.0  3000     NaN     0.0
콜롬비아  110   5000.0  5000     NaN     0.0

In [541]:
df.groupby(['원산지','칼로리']).mean(numeric_only=True).reset_index()

     원산지   칼로리      가격    이벤트가
0   과테말라    20  4000.0     NaN
1   과테말라   110  5000.0  1000.0
2   과테말라   210  5900.0     NaN
3   과테말라   250  5500.0  1000.0
4   대한민국     0  5300.0     NaN
5  코스타리카  1100  3000.0     NaN
6   콜롬비아   110  5000.0     NaN

In [542]:
import pandas as pd

In [543]:
df=pd.DataFrame({'과일':['딸기','블루베리','딸기','블루베리','딸기','블루베리','딸기','블루베리'],
                 '가격':[1000,None,1500,None,2000,2500,None,1800]})

In [544]:
df

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [545]:
price=df.groupby('과일')['가격'].transform('mean')

In [546]:
price

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: 가격, dtype: float64

In [547]:
df['가격']=df['가격'].fillna(price)

In [548]:
df

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [549]:
df=pd.DataFrame({'과일':['딸기','블루베리','딸기','블루베리','딸기','블루베리','딸기','블루베리'],
                 '등급':['B','B','A','A','A','A','B','B'],
                 '가격':[1000,None,1500,None,2000,2500,None,1800],
                 })

In [550]:
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B     NaN
2    딸기  A  1500.0
3  블루베리  A     NaN
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B     NaN
7  블루베리  B  1800.0

In [551]:
price=df.groupby(['과일','등급'])['가격'].transform('mean')

In [552]:
price

0    1000.0
1    1800.0
2    1750.0
3    2500.0
4    1750.0
5    2500.0
6    1000.0
7    1800.0
Name: 가격, dtype: float64

In [553]:
df['가격']=df['가격'].fillna(price)

In [554]:
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B  1800.0
2    딸기  A  1500.0
3  블루베리  A  2500.0
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B  1000.0
7  블루베리  B  1800.0

In [555]:
import pandas as pd

In [556]:
df=pd.DataFrame({'커피종류':['아메리카노','아메리카노','아메리카노','라떼','라떼','라떼'],
                 '컵크기':['Small','Medium','Large','Small','Medium','Large'],
                 '판매량':[120,150,200,100,130,180]})

In [557]:
df

    커피종류     컵크기  판매량
0  아메리카노   Small  120
1  아메리카노  Medium  150
2  아메리카노   Large  200
3     라떼   Small  100
4     라떼  Medium  130
5     라떼   Large  180

In [558]:
grouped=df.groupby(['커피종류','컵크기'])['판매량'].sum()

In [559]:
grouped

커피종류   컵크기
라떼     Large     180
       Medium    130
       Small     100
아메리카노  Large     200
       Medium    150
       Small     120
Name: 판매량, dtype: int64

In [560]:
grouped.unstack().unstack()

컵크기     커피종류
Large   라떼       180
        아메리카노    200
Medium  라떼       130
        아메리카노    150
Small   라떼       100
        아메리카노    120
dtype: int64

In [561]:
import pandas as pd
data={'Data1':['2024-02-17','2024-02-18','2024-02-19','2024-02-20'],
      'Data2':['2024:02:17','2024:02:18','2024:02:19','2024:02:20'],
      'Data3':['24/02/17','24/02/18','24/02/19','24/02/20'],
      'Data4':['02/17/2024','02/18/2024','02/19/2024','02/20/2024'],
      'Data5':['17-Feb-2024','18-Feb-2024','19-Feb-2024','20-Feb-2024'],
      'DateTime1':['2024-02-17 13:50:30','2024-02-18 14:55:45','2024-02-19 03:30:15','2024-02-20 16:10:50'],
      'DataTime2':['2024-02-17','2024-02-18','2024-02-19','2024-02-20'],
      'DataTime3':['2024-02-17','2024-02-18','2024-02-19','2024-02-20'],
      'DataTime4':['2024-02-17','2024-02-18','2024-02-19','2024-02-20']}

In [562]:
data

{'Data1': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
 'Data2': ['2024:02:17', '2024:02:18', '2024:02:19', '2024:02:20'],
 'Data3': ['24/02/17', '24/02/18', '24/02/19', '24/02/20'],
 'Data4': ['02/17/2024', '02/18/2024', '02/19/2024', '02/20/2024'],
 'Data5': ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024', '20-Feb-2024'],
 'DateTime1': ['2024-02-17 13:50:30',
  '2024-02-18 14:55:45',
  '2024-02-19 03:30:15',
  '2024-02-20 16:10:50'],
 'DataTime2': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
 'DataTime3': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
 'DataTime4': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20']}

In [563]:
df=pd.DataFrame(data)

In [564]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20

In [565]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data1      4 non-null      object
 1   Data2      4 non-null      object
 2   Data3      4 non-null      object
 3   Data4      4 non-null      object
 4   Data5      4 non-null      object
 5   DateTime1  4 non-null      object
 6   DataTime2  4 non-null      object
 7   DataTime3  4 non-null      object
 8   DataTime4  4 non-null      object
dtypes: object(9)
memory usage: 420.0+ bytes

In [566]:
df.to_csv('date_data.csv',index=False)

In [567]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20

In [568]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20

In [569]:
df=pd.read_csv('date_data.csv')

In [570]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20

In [571]:
df['Data1']=pd.to_datetime(df['Data1'])
df['Data2']=pd.to_datetime(df['Data2'],format='%Y:%m:%d')
df['Data3']=pd.to_datetime(df['Data3'])
df['Data3']=pd.to_datetime(df['Data3'])
df['Data4']=pd.to_datetime(df['Data4'])
df['Data5']=pd.to_datetime(df['Data5'])
df['DateTime1']=pd.to_datetime(df['DateTime1'])
df['DataTime2']=pd.to_datetime(df['DataTime2'])
df['DataTime3']=pd.to_datetime(df['DataTime3'])
df['DataTime4']=pd.to_datetime(df['DataTime4'])

/tmp/ipykernel_11500/873710502.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Data3']=pd.to_datetime(df['Data3'])

In [572]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data1      4 non-null      datetime64[ns]
 1   Data2      4 non-null      datetime64[ns]
 2   Data3      4 non-null      datetime64[ns]
 3   Data4      4 non-null      datetime64[ns]
 4   Data5      4 non-null      datetime64[ns]
 5   DateTime1  4 non-null      datetime64[ns]
 6   DataTime2  4 non-null      datetime64[ns]
 7   DataTime3  4 non-null      datetime64[ns]
 8   DataTime4  4 non-null      datetime64[ns]
dtypes: datetime64[ns](9)
memory usage: 420.0 bytes

In [573]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data1      4 non-null      datetime64[ns]
 1   Data2      4 non-null      datetime64[ns]
 2   Data3      4 non-null      datetime64[ns]
 3   Data4      4 non-null      datetime64[ns]
 4   Data5      4 non-null      datetime64[ns]
 5   DateTime1  4 non-null      datetime64[ns]
 6   DataTime2  4 non-null      datetime64[ns]
 7   DataTime3  4 non-null      datetime64[ns]
 8   DataTime4  4 non-null      datetime64[ns]
dtypes: datetime64[ns](9)
memory usage: 420.0 bytes

In [574]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024-02-17,2017-02-24,2024-02-17,2024-02-17,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024-02-18,2018-02-24,2024-02-18,2024-02-18,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024-02-19,2019-02-24,2024-02-19,2024-02-19,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024-02-20,2020-02-24,2024-02-20,2024-02-20,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20

In [575]:
df=pd.read_csv('date_data.csv')

In [576]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20

In [577]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data1      4 non-null      object
 1   Data2      4 non-null      object
 2   Data3      4 non-null      object
 3   Data4      4 non-null      object
 4   Data5      4 non-null      object
 5   DateTime1  4 non-null      object
 6   DataTime2  4 non-null      object
 7   DataTime3  4 non-null      object
 8   DataTime4  4 non-null      object
dtypes: object(9)
memory usage: 420.0+ bytes

In [578]:
df['Data1']=pd.to_datetime(df['Data1'])
df['Data2']=pd.to_datetime(df['Data2'],format='%Y:%m:%d')
df['Data3']=pd.to_datetime(df['Data3'])
df['Data4']=pd.to_datetime(df['Data4'])
df['Data5']=pd.to_datetime(df['Data5'])
df['DataTime1']=pd.to_datetime(df['DateTime1'],format='%Y-%m-%d %H:%M:%S')
df['DataTime2']=pd.to_datetime(df['DataTime2'])
df['DataTime3']=pd.to_datetime(df['DataTime3'])
df['DataTime4']=pd.to_datetime(df['DataTime4'])

/tmp/ipykernel_11500/1822885798.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Data3']=pd.to_datetime(df['Data3'])

In [579]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Data1      4 non-null      datetime64[ns]
 1   Data2      4 non-null      datetime64[ns]
 2   Data3      4 non-null      datetime64[ns]
 3   Data4      4 non-null      datetime64[ns]
 4   Data5      4 non-null      datetime64[ns]
 5   DateTime1  4 non-null      object
 6   DataTime2  4 non-null      datetime64[ns]
 7   DataTime3  4 non-null      datetime64[ns]
 8   DataTime4  4 non-null      datetime64[ns]
 9   DataTime1  4 non-null      datetime64[ns]
dtypes: datetime64[ns](9), object(1)
memory usage: 452.0+ bytes

In [580]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4,DataTime1
0,2024-02-17,2024-02-17,2017-02-24,2024-02-17,2024-02-17,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17,2024-02-17 13:50:30
1,2024-02-18,2024-02-18,2018-02-24,2024-02-18,2024-02-18,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18,2024-02-18 14:55:45
2,2024-02-19,2024-02-19,2019-02-24,2024-02-19,2024-02-19,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19,2024-02-19 03:30:15
3,2024-02-20,2024-02-20,2020-02-24,2024-02-20,2024-02-20,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20,2024-02-20 16:10:50

In [581]:
df['year']=df['DataTime2'].dt.year
df['month']=df['DataTime2'].dt.month
df['day']=df['DataTime2'].dt.day

In [582]:
df

,Data1,Data2,Data3,Data4,Data5,DateTime1,DataTime2,DataTime3,DataTime4,DataTime1,year,month,day
0,2024-02-17,2024-02-17,2017-02-24,2024-02-17,2024-02-17,2024-02-17 13:50:30,2024-02-17,2024-02-17,2024-02-17,2024-02-17 13:50:30,2024,2,17
1,2024-02-18,2024-02-18,2018-02-24,2024-02-18,2024-02-18,2024-02-18 14:55:45,2024-02-18,2024-02-18,2024-02-18,2024-02-18 14:55:45,2024,2,18
2,2024-02-19,2024-02-19,2019-02-24,2024-02-19,2024-02-19,2024-02-19 03:30:15,2024-02-19,2024-02-19,2024-02-19,2024-02-19 03:30:15,2024,2,19
3,2024-02-20,2024-02-20,2020-02-24,2024-02-20,2024-02-20,2024-02-20 16:10:50,2024-02-20,2024-02-20,2024-02-20,2024-02-20 16:10:50,2024,2,20

In [583]:
df['DataTime2'].dt.dayofweek

0    5
1    6
2    0
3    1
Name: DataTime2, dtype: int32

In [587]:
df['DataTime2'].dt.to_period('Q')

0    2024Q1
1    2024Q1
2    2024Q1
3    2024Q1
Name: DataTime2, dtype: period[Q-DEC]

In [594]:
df=pd.read_csv('date_data.csv',usecols=['DataTime4'],parse_dates=['DataTime4'])

In [596]:
day=pd.Timedelta(days=99)
df['100day']=df['DataTime4']+day
df

   DataTime4     100day
0 2024-02-17 2024-05-26
1 2024-02-18 2024-05-27
2 2024-02-19 2024-05-28
3 2024-02-20 2024-05-29

In [597]:
hour=pd.Timedelta(hours=100)
df['100hours']=df['DataTime4']+hour
df

   DataTime4     100day            100hours
0 2024-02-17 2024-05-26 2024-02-21 04:00:00
1 2024-02-18 2024-05-27 2024-02-22 04:00:00
2 2024-02-19 2024-05-28 2024-02-23 04:00:00
3 2024-02-20 2024-05-29 2024-02-24 04:00:00

In [602]:
diff=pd.Timedelta(weeks=7,days=7,hours=7,minutes=7,seconds=7)
df['difference']=df['DataTime4']-diff
df

   DataTime4     100day            100hours          difference
0 2024-02-17 2024-05-26 2024-02-21 04:00:00 2023-12-22 16:52:53
1 2024-02-18 2024-05-27 2024-02-22 04:00:00 2023-12-23 16:52:53
2 2024-02-19 2024-05-28 2024-02-23 04:00:00 2023-12-24 16:52:53
3 2024-02-20 2024-05-29 2024-02-24 04:00:00 2023-12-25 16:52:53

In [607]:
diff2=df['100day']-df['100hours']

In [608]:
df

,DataTime4,100day,100hours,difference,diff2
0,2024-02-17,2024-05-26,2024-02-21 04:00:00,2023-12-22 16:52:53,94 days 20:00:00
1,2024-02-18,2024-05-27,2024-02-22 04:00:00,2023-12-23 16:52:53,94 days 20:00:00
2,2024-02-19,2024-05-28,2024-02-23 04:00:00,2023-12-24 16:52:53,94 days 20:00:00
3,2024-02-20,2024-05-29,2024-02-24 04:00:00,2023-12-25 16:52:53,94 days 20:00:00

In [609]:
diff2

0   94 days 20:00:00
1   94 days 20:00:00
2   94 days 20:00:00
3   94 days 20:00:00
dtype: timedelta64[ns]

In [613]:
print(diff2.dt.total_seconds())
print(diff2.dt.total_seconds()/60)

0    8193600.0
1    8193600.0
2    8193600.0
3    8193600.0
dtype: float64
0    136560.0
1    136560.0
2    136560.0
3    136560.0
dtype: float64

In [614]:
print(diff2.dt.days)

0    94
1    94
2    94
3    94
dtype: int64

In [620]:
print(diff2.dt.total_seconds())
print(diff2.dt.seconds)

0    8193600.0
1    8193600.0
2    8193600.0
3    8193600.0
dtype: float64
0    72000
1    72000
2    72000
3    72000
dtype: int32

In [621]:
min=5.41

In [622]:
print(int(min),'분')

5 분

In [623]:
print(0.41*60,'초')

24.599999999999998 초

In [624]:
import pandas as pd
appetizer=pd.DataFrame({
    'Menu':['Salad','Soup','Bread'],
    'Price':[5000,3000,2000]
})

In [625]:
appetizer

    Menu  Price
0  Salad   5000
1   Soup   3000
2  Bread   2000

In [626]:
main=pd.DataFrame({
    'Menu':['Steak','Pasta','Chicken'],
    'Price':[15000,12000,10000]
})

In [627]:
main

      Menu  Price
0    Steak  15000
1    Pasta  12000
2  Chicken  10000

In [629]:
print(appetizer)
print(main)

    Menu  Price
0  Salad   5000
1   Soup   3000
2  Bread   2000
      Menu  Price
0    Steak  15000
1    Pasta  12000
2  Chicken  10000

In [631]:
full_menu=pd.concat([appetizer,main],ignore_index=True)

In [632]:
full_menu

      Menu  Price
0    Salad   5000
1     Soup   3000
2    Bread   2000
3    Steak  15000
4    Pasta  12000
5  Chicken  10000

In [638]:
full_menu=pd.concat([appetizer,main],axis=1)

In [639]:
full_menu

    Menu  Price     Menu  Price
0  Salad   5000    Steak  15000
1   Soup   3000    Pasta  12000
2  Bread   2000  Chicken  10000

In [640]:
price=pd.DataFrame({
    'Menu':['Salad','Soup','Steak','Pasta'],
    'Price':[5000,3000,15000,12000]
})

In [641]:
price

    Menu  Price
0  Salad   5000
1   Soup   3000
2  Steak  15000
3  Pasta  12000

In [642]:
cal=pd.DataFrame({
    'Menu':['Soup','Steak','Pasta','Salad'],
    'Calories':[100,500,400,150]
})

In [643]:
cal

    Menu  Calories
0   Soup       100
1  Steak       500
2  Pasta       400
3  Salad       150

In [644]:
menu_info=pd.merge(price,cal,on='Menu')

In [645]:
menu_info

    Menu  Price  Calories
0  Salad   5000       150
1   Soup   3000       100
2  Steak  15000       500
3  Pasta  12000       400

In [646]:
import pandas as pd

In [647]:
data={'이름':['서우','다인','채아','예담','종현','태헌'],
      '부서':['개발','기획','개발','기획','개발','기획'],
      '급여':[3000,3200,3100,3300,2900,3100]}

In [648]:
data

{'이름': ['서우', '다인', '채아', '예담', '종현', '태헌'],
 '부서': ['개발', '기획', '개발', '기획', '개발', '기획'],
 '급여': [3000, 3200, 3100, 3300, 2900, 3100]}

In [649]:
pd.DataFrame(data)

   이름  부서    급여
0  서우  개발  3000
1  다인  기획  3200
2  채아  개발  3100
3  예담  기획  3300
4  종현  개발  2900
5  태헌  기획  3100

In [650]:
df=pd.DataFrame(data)

In [651]:
df

   이름  부서    급여
0  서우  개발  3000
1  다인  기획  3200
2  채아  개발  3100
3  예담  기획  3300
4  종현  개발  2900
5  태헌  기획  3100

In [653]:
print('[원본데이터]')
print(df)

[원본데이터]
   이름  부서    급여
0  서우  개발  3000
1  다인  기획  3200
2  채아  개발  3100
3  예담  기획  3300
4  종현  개발  2900
5  태헌  기획  3100

In [654]:
pt=df.pivot_table(index='부서',values='급여',aggfunc='mean')

In [661]:
print('|n [부서별 평균 급여]')
print(pt)

|n [부서별 평균 급여]
        급여
부서
개발  3000.0
기획  3200.0

In [662]:
data={'부서':['개발','기획','기획','기획','개발','개발'],
      '직급':['대리','과장','대리','과장','대리','과장'],
      '급여':[3000,4000,3200,4200,3500,4500]}

In [663]:
df=pd.DataFrame(data)

In [664]:
df

   부서  직급    급여
0  개발  대리  3000
1  기획  과장  4000
2  기획  대리  3200
3  기획  과장  4200
4  개발  대리  3500
5  개발  과장  4500

In [665]:
print('[원본데이터]')
print(df)

[원본데이터]
   부서  직급    급여
0  개발  대리  3000
1  기획  과장  4000
2  기획  대리  3200
3  기획  과장  4200
4  개발  대리  3500
5  개발  과장  4500

In [668]:
pt=df.pivot_table(index='부서',columns='직급',values='급여',aggfunc='mean')

In [669]:
pt

직급      과장      대리
부서
개발  4500.0  3250.0
기획  4100.0  3200.0

In [670]:
import pandas as pd
df=pd.DataFrame({
    '구분':['전자','전자','전자','전자','전자','가전','가전','가전','가전'],
    '유형':['일반','일반','일반','특수','특수','일반','일반','특수','특수'],
    '크기':['소형','대형','대형','소형','소형','대형','소형','소형','대형'],
    '수량':[1,2,2,3,3,4,5,6,7,],
    '금액':[2,4,5,5,6,6,8,9,9,]
})

In [671]:
df

   구분  유형  크기  수량  금액
0  전자  일반  소형   1   2
1  전자  일반  대형   2   4
2  전자  일반  대형   2   5
3  전자  특수  소형   3   5
4  전자  특수  소형   3   6
5  가전  일반  대형   4   6
6  가전  일반  소형   5   8
7  가전  특수  소형   6   9
8  가전  특수  대형   7   9

In [675]:
pt=df.pivot_table(index=['구분','유형'],columns=['크기'],values=['수량'],aggfunc='sum',fill_value=0)

In [676]:
pt

      수량
크기    대형 소형
구분 유형
가전 일반  4  5
   특수  7  6
전자 일반  4  1
   특수  0  6

In [681]:
pt=df.pivot_table(index=['구분','크기'],values=['수량','금액'],aggfunc={'수량':'mean','금액':'mean'})

In [682]:
pt

             금액        수량
구분 크기
가전 대형  7.500000  5.500000
   소형  8.500000  5.500000
전자 대형  4.500000  2.000000
   소형  4.333333  2.333333