<a href="https://colab.research.google.com/github/gumurytv/bigdataCert/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0_%EC%8B%A4%EA%B8%B0_PART1_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [200]:
import pandas as pd

In [201]:
menu=pd.Series(['비빔밥','김치찌개','된장찌개'])

In [202]:
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [203]:
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [204]:
price=pd.Series([10000,9000,8000])

In [205]:
price

0    10000
1     9000
2     8000
dtype: int64

In [206]:
df=pd.DataFrame({'메뉴':['비빔밥','김치찌개','된장찌개'],
                 '가격':[10000,9000,8000],
                 '원산지':['국내산','국내산','국내산']})

In [207]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [208]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [209]:
df[['메뉴']]

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [210]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [211]:
df[['메뉴','가격']]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [212]:
cols=['메뉴','가격']

In [213]:
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [214]:
type[df]

type[     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산]

In [215]:
type(df)

pandas.core.frame.DataFrame

In [216]:
print('df:',type(df))

df: <class 'pandas.core.frame.DataFrame'>

In [217]:
df=pd.DataFrame({
    '메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    '가격':[4500,5000,5500,5000,4000,5900,5300],
    '칼로리':[10,110,250,110,20,210,0]
})

In [218]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [219]:
df.to_csv('temp.csv')

In [220]:
temp_df=pd.read_csv('temp.csv')

In [221]:
temp_df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [222]:
df.to_csv('cafe.csv',index=False)

In [223]:
df=pd.read_csv('cafe.csv')

In [224]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [225]:
df.shape

(7, 3)

In [226]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [227]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [228]:
df_car=pd.DataFrame({'car':['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
                  'size':['S','M','S','S','M','M','L','S','S','M','S']})

In [229]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [230]:
df_car

      car size
0   Sedan    S
1     SUV    M
2   Sedan    S
3     SUV    S
4     SUV    M
5     SUV    M
6   Sedan    L
7   Sedan    S
8   Sedan    S
9   Sedan    M
10  Sedan    S

In [231]:
df_car.head(3)

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S

In [232]:
df_car.nunique()

car     2
size    3
dtype: int64

In [233]:
print(df_car['car'].unique())

['Sedan' 'SUV']

In [234]:
print(df_car['size'].unique())

['S' 'M' 'L']

In [235]:
df_car['car'].value_counts()

car
Sedan    7
SUV      4
Name: count, dtype: int64

In [236]:
df.value_counts()

메뉴     가격    칼로리
녹차     5300  0      1
밀크티    5900  210    1
아메리카노  4500  10     1
에스프레소  4000  20     1
카페라떼   5000  110    1
카페모카   5500  250    1
카푸치노   5000  110    1
Name: count, dtype: int64

In [237]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [238]:
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [239]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [240]:
data={
    '메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    '가격':[4500,5000,5500,5000,4000,5900,5300],
    '칼로리':['10','110','250','110','20','210','0']
}

In [241]:
df=pd.DataFrame(data)

In [242]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [243]:
data

{'메뉴': ['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
 '가격': [4500, 5000, 5500, 5000, 4000, 5900, 5300],
 '칼로리': ['10', '110', '250', '110', '20', '210', '0']}

In [244]:
df['가격']=df['가격'].astype('int')

In [245]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [246]:
df['칼로리']=df['칼로리'].astype('float')

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [248]:
df=pd.read_csv('cafe.csv')

In [249]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [250]:
df['new']=0

In [251]:
df.head()

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0
2   카페모카  5500  250    0
3   카푸치노  5000  110    0
4  에스프레소  4000   20    0

In [252]:
discount=0.2

In [253]:
df['할인가']=df['가격']*(1-discount)

In [254]:
df

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0
4  에스프레소  4000   20    0  3200.0
5    밀크티  5900  210    0  4720.0
6     녹차  5300    0    0  4240.0

In [255]:
df=pd.read_csv('cafe.csv')

In [256]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [257]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [258]:
df.drop(1,axis=0,inplace=True)

In [259]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [260]:
df=df.drop('메뉴',axis=1)

In [261]:
df

     가격  칼로리
0  4500   10
2  5500  250
3  5000  110
4  4000   20
5  5900  210
6  5300    0

In [262]:
df=pd.read_csv('cafe.csv')

In [263]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [264]:
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [265]:
df.loc[1,'가격']

np.int64(5000)

In [266]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [267]:
df.loc[2,'메뉴':'칼로리']

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [268]:
df.loc[2,['메뉴','칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [269]:
df.loc[1:3,['메뉴','칼로리']]

     메뉴  칼로리
1  카페라떼  110
2  카페모카  250
3  카푸치노  110

In [270]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [271]:
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [272]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [273]:
df.to_csv('cafe.csv')

In [274]:
df=pd.read_csv('cafe.csv')

In [275]:
df

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [276]:
df.head(2)

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110

In [277]:
df.loc[0]

Unnamed: 0        0
메뉴            아메리카노
가격             4500
칼로리              10
Name: 0, dtype: object

In [278]:
df.loc[1]

Unnamed: 0       1
메뉴            카페라떼
가격            5000
칼로리            110
Name: 1, dtype: object

In [279]:
df.loc[0,'가격']

np.int64(4500)

In [280]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [281]:
df.loc[0:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [282]:
df.loc[1:,'가격']

1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [283]:
 df.loc[2,'메뉴':'칼로리']

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [284]:
df.loc[2,['메뉴','칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [285]:
df

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [286]:
df.drop(0,axis=0,inplace=True)

In [287]:
df

   Unnamed: 0     메뉴    가격  칼로리
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210
6           6     녹차  5300    0

In [288]:
df.iloc[0]

Unnamed: 0       1
메뉴            카페라떼
가격            5000
칼로리            110
Name: 1, dtype: object

In [289]:
df.iloc[1:3]

   Unnamed: 0    메뉴    가격  칼로리
2           2  카페모카  5500  250
3           3  카푸치노  5000  110

In [290]:
df.head()

   Unnamed: 0     메뉴    가격  칼로리
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20
5           5    밀크티  5900  210

In [291]:
df.iloc[1:4]

   Unnamed: 0     메뉴    가격  칼로리
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [292]:
df.loc[2:4,'메뉴':'칼로리']

      메뉴    가격  칼로리
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [293]:
df.head(2)

   Unnamed: 0    메뉴    가격  칼로리
1           1  카페라떼  5000  110
2           2  카페모카  5500  250

In [294]:
import numpy as np

In [295]:
df['원산지']=np.nan

In [296]:
df

   Unnamed: 0     메뉴    가격  칼로리  원산지
1           1   카페라떼  5000  110  NaN
2           2   카페모카  5500  250  NaN
3           3   카푸치노  5000  110  NaN
4           4  에스프레소  4000   20  NaN
5           5    밀크티  5900  210  NaN
6           6     녹차  5300    0  NaN

In [297]:
df

   Unnamed: 0     메뉴    가격  칼로리  원산지
1           1   카페라떼  5000  110  NaN
2           2   카페모카  5500  250  NaN
3           3   카푸치노  5000  110  NaN
4           4  에스프레소  4000   20  NaN
5           5    밀크티  5900  210  NaN
6           6     녹차  5300    0  NaN

In [298]:
df.loc[1,'원산지']='콜롬비아'

/tmp/ipykernel_1827/3595826506.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[1,'원산지']='콜롬비아'

In [299]:
df

   Unnamed: 0     메뉴    가격  칼로리   원산지
1           1   카페라떼  5000  110  콜롬비아
2           2   카페모카  5500  250   NaN
3           3   카푸치노  5000  110   NaN
4           4  에스프레소  4000   20   NaN
5           5    밀크티  5900  210   NaN
6           6     녹차  5300    0   NaN

In [300]:
df.loc[2:6,'원산지']='과테말라'

In [301]:
df

   Unnamed: 0     메뉴    가격  칼로리   원산지
1           1   카페라떼  5000  110  콜롬비아
2           2   카페모카  5500  250  과테말라
3           3   카푸치노  5000  110  과테말라
4           4  에스프레소  4000   20  과테말라
5           5    밀크티  5900  210  과테말라
6           6     녹차  5300    0  과테말라

In [302]:
df.loc['시즌']=['크리스마스라떼',1,6000,300,'한국']

In [303]:
df

   Unnamed: 0     메뉴    가격  칼로리   원산지
1           1   카페라떼  5000  110  콜롬비아
2           2   카페모카  5500  250  과테말라
3           3   카푸치노  5000  110  과테말라
4           4  에스프레소  4000   20  과테말라
5           5    밀크티  5900  210  과테말라
6           6     녹차  5300    0  과테말라
시즌    크리스마스라떼      1  6000  300    한국

In [304]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [305]:
df

       메뉴    가격  칼로리   원산지
1    카페라떼  5000  110  콜롬비아
2    카페모카  5500  250  과테말라
3    카푸치노  5000  110  과테말라
4   에스프레소  4000   20  과테말라
5     밀크티  5900  210  과테말라
6      녹차  5300    0  과테말라
시즌      1  6000  300    한국

In [306]:
df.loc[7]={'메뉴':'딴짓커피','가격':'3000','칼로리':'1100'}

In [307]:
df

       메뉴    가격   칼로리   원산지
1    카페라떼  5000   110  콜롬비아
2    카페모카  5500   250  과테말라
3    카푸치노  5000   110  과테말라
4   에스프레소  4000    20  과테말라
5     밀크티  5900   210  과테말라
6      녹차  5300     0  과테말라
시즌      1  6000   300    한국
7    딴짓커피  3000  1100   NaN

In [308]:
df.drop('시즌',axis=0,inplace=True)

In [309]:
df

      메뉴    가격   칼로리   원산지
1   카페라떼  5000   110  콜롬비아
2   카페모카  5500   250  과테말라
3   카푸치노  5000   110  과테말라
4  에스프레소  4000    20  과테말라
5    밀크티  5900   210  과테말라
6     녹차  5300     0  과테말라
7   딴짓커피  3000  1100   NaN

In [310]:
df.to_csv('cafe2.csv',index=False)

In [311]:
df=pd.read_csv('cafe2.csv')

In [312]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [313]:
df.sort_index(ascending=False)

      메뉴    가격   칼로리   원산지
6   딴짓커피  3000  1100   NaN
5     녹차  5300     0  과테말라
4    밀크티  5900   210  과테말라
3  에스프레소  4000    20  과테말라
2   카푸치노  5000   110  과테말라
1   카페모카  5500   250  과테말라
0   카페라떼  5000   110  콜롬비아

In [314]:
df.sort_values('가격',ascending=False)

      메뉴    가격   칼로리   원산지
4    밀크티  5900   210  과테말라
1   카페모카  5500   250  과테말라
5     녹차  5300     0  과테말라
2   카푸치노  5000   110  과테말라
0   카페라떼  5000   110  콜롬비아
3  에스프레소  4000    20  과테말라
6   딴짓커피  3000  1100   NaN

In [315]:
df.sort_values(['가격','메뉴'],ascending=[False,True],inplace=True)

In [316]:
df

      메뉴    가격   칼로리   원산지
4    밀크티  5900   210  과테말라
1   카페모카  5500   250  과테말라
5     녹차  5300     0  과테말라
0   카페라떼  5000   110  콜롬비아
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
6   딴짓커피  3000  1100   NaN

In [317]:
df.reset_index(drop=True)

      메뉴    가격   칼로리   원산지
0    밀크티  5900   210  과테말라
1   카페모카  5500   250  과테말라
2     녹차  5300     0  과테말라
3   카페라떼  5000   110  콜롬비아
4   카푸치노  5000   110  과테말라
5  에스프레소  4000    20  과테말라
6   딴짓커피  3000  1100   NaN

In [318]:
df=pd.read_csv('cafe2.csv')

In [319]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [320]:
df['칼로리']<50

0    False
1    False
2    False
3     True
4    False
5     True
6    False
Name: 칼로리, dtype: bool

In [321]:
cond=df['칼로리']<50

In [322]:
df[cond]

      메뉴    가격  칼로리   원산지
3  에스프레소  4000   20  과테말라
5     녹차  5300    0  과테말라

In [323]:
df[~cond]

     메뉴    가격   칼로리   원산지
0  카페라떼  5000   110  콜롬비아
1  카페모카  5500   250  과테말라
2  카푸치노  5000   110  과테말라
4   밀크티  5900   210  과테말라
6  딴짓커피  3000  1100   NaN

In [324]:
cond1=df['가격']>=5000
cond2=df['칼로리']>100
df[cond1&cond2]

     메뉴    가격  칼로리   원산지
0  카페라떼  5000  110  콜롬비아
1  카페모카  5500  250  과테말라
2  카푸치노  5000  110  과테말라
4   밀크티  5900  210  과테말라

In [325]:
cond1=df['가격']>=5000
cond2=df['칼로리']>100
df[cond1|cond2]

     메뉴    가격   칼로리   원산지
0  카페라떼  5000   110  콜롬비아
1  카페모카  5500   250  과테말라
2  카푸치노  5000   110  과테말라
4   밀크티  5900   210  과테말라
5    녹차  5300     0  과테말라
6  딴짓커피  3000  1100   NaN

In [326]:
cond=df['원산지']=='과테말라'

In [327]:
df[cond]

      메뉴    가격  칼로리   원산지
1   카페모카  5500  250  과테말라
2   카푸치노  5000  110  과테말라
3  에스프레소  4000   20  과테말라
4    밀크티  5900  210  과테말라
5     녹차  5300    0  과테말라

In [328]:
cond2=df['가격']<=5000

In [329]:
df[cond&cond2]

      메뉴    가격  칼로리   원산지
2   카푸치노  5000  110  과테말라
3  에스프레소  4000   20  과테말라

In [330]:
cond=df['메뉴'].isin(['녹차'])

In [331]:
df[cond]

   메뉴    가격  칼로리   원산지
5  녹차  5300    0  과테말라

In [332]:
box=['녹차','카푸치노','카페라떼']

In [333]:
cond=df.isin(box)

In [334]:
df[cond]

     메뉴  가격  칼로리  원산지
0  카페라떼 NaN  NaN  NaN
1   NaN NaN  NaN  NaN
2  카푸치노 NaN  NaN  NaN
3   NaN NaN  NaN  NaN
4   NaN NaN  NaN  NaN
5    녹차 NaN  NaN  NaN
6   NaN NaN  NaN  NaN

In [335]:
df=pd.read_csv('cafe2.csv')

In [336]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [337]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False   True

In [338]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False  False  False
6  False  False  False   True

In [339]:
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    1
dtype: int64

In [340]:
df.isna().sum()

메뉴     0
가격     0
칼로리    0
원산지    1
dtype: int64

In [341]:
df

      메뉴    가격   칼로리   원산지
0   카페라떼  5000   110  콜롬비아
1   카페모카  5500   250  과테말라
2   카푸치노  5000   110  과테말라
3  에스프레소  4000    20  과테말라
4    밀크티  5900   210  과테말라
5     녹차  5300     0  과테말라
6   딴짓커피  3000  1100   NaN

In [342]:
df['원산지'].fillna('코스타리카',inplace=True)

/tmp/ipykernel_1827/3660102855.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['원산지'].fillna('코스타리카',inplace=True)

In [343]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [344]:
df.to_csv('cafe3.csv',index=False)

In [345]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [346]:
df=pd.read_csv('cafe3.csv')

In [347]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [348]:
df.replace('아메리카노','룽고',inplace=True)

In [349]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [350]:
df.replace('녹차','그린티',inplace=True)

In [351]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1   카페모카  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5    그린티  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [352]:
change={'카페모카':'아메리카노','그린티':'녹차'}

In [353]:
df.replace(change,inplace=True)

In [354]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1  아메리카노  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   과테말라
6   딴짓커피  3000  1100  코스타리카

In [355]:
df.loc[5,'원산지']='대한민국'

In [356]:
df

      메뉴    가격   칼로리    원산지
0   카페라떼  5000   110   콜롬비아
1  아메리카노  5500   250   과테말라
2   카푸치노  5000   110   과테말라
3  에스프레소  4000    20   과테말라
4    밀크티  5900   210   과테말라
5     녹차  5300     0   대한민국
6   딴짓커피  3000  1100  코스타리카

In [357]:
df.loc[1:2,'이벤트가']=1000

In [358]:
df

      메뉴    가격   칼로리    원산지    이벤트가
0   카페라떼  5000   110   콜롬비아     NaN
1  아메리카노  5500   250   과테말라  1000.0
2   카푸치노  5000   110   과테말라  1000.0
3  에스프레소  4000    20   과테말라     NaN
4    밀크티  5900   210   과테말라     NaN
5     녹차  5300     0   대한민국     NaN
6   딴짓커피  3000  1100  코스타리카     NaN

In [359]:
df.to_csv('cafe4.csv')

In [360]:
import pandas as pd

In [379]:
df=pd.DataFrame({'A':['데이터 분석','기본 학습서','퇴근 후 열공'],
                 'B':[10,20,30],
                 'C':['ab cd','AB CD','ab cd ']})

In [380]:
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [381]:
df.replace('분석','시각화')

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [382]:
df['A']=df['A'].str.replace('분석','시각화')

In [383]:
df

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [384]:
df['B']=df['B'].replace(10,100)

In [385]:
df

         A    B       C
0  데이터 시각화  100   ab cd
1   기본 학습서   20   AB CD
2  퇴근 후 열공   30  ab cd

In [386]:
df['B']=df['B'].str.replace(20,200)

AttributeError: Can only use .str accessor with string values!

In [387]:
df['A'].str.split()

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [388]:
df['A'].str.split()[2]

['퇴근', '후', '열공']

In [390]:
df['D']=df['A'].str.split().str[0]

In [391]:
df

         A    B       C    D
0  데이터 시각화  100   ab cd  데이터
1   기본 학습서   20   AB CD   기본
2  퇴근 후 열공   30  ab cd    퇴근

In [392]:
df['A'].str.contains('기본')

0    False
1     True
2    False
Name: A, dtype: bool

In [394]:
df['기본포함여부']=df['A'].str.contains('기본')

In [395]:
df

         A    B       C    D  기본포함여부
0  데이터 시각화  100   ab cd  데이터   False
1   기본 학습서   20   AB CD   기본    True
2  퇴근 후 열공   30  ab cd    퇴근   False

In [396]:
df

         A    B       C    D  기본포함여부
0  데이터 시각화  100   ab cd  데이터   False
1   기본 학습서   20   AB CD   기본    True
2  퇴근 후 열공   30  ab cd    퇴근   False

In [397]:
df['문자길이']=df['A'].str.len()

In [398]:
df

         A    B       C    D  기본포함여부  문자길이
0  데이터 시각화  100   ab cd  데이터   False     7
1   기본 학습서   20   AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd    퇴근   False     7

In [399]:
'AB cd'=='ab CD'

False

In [400]:
df

         A    B       C    D  기본포함여부  문자길이
0  데이터 시각화  100   ab cd  데이터   False     7
1   기본 학습서   20   AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd    퇴근   False     7

In [404]:
df['C']=df['C'].str.lower()

In [405]:
df

         A    B       C    D  기본포함여부  문자길이
0  데이터 시각화  100   ab cd  데이터   False     7
1   기본 학습서   20   ab cd   기본    True     6
2  퇴근 후 열공   30  ab cd    퇴근   False     7

In [406]:
df['C']=df['C'].str.upper()

In [407]:
df

         A    B       C    D  기본포함여부  문자길이
0  데이터 시각화  100   AB CD  데이터   False     7
1   기본 학습서   20   AB CD   기본    True     6
2  퇴근 후 열공   30  AB CD    퇴근   False     7

In [408]:
df['C']=='AB CD'

0     True
1     True
2    False
Name: C, dtype: bool

In [409]:
df['C']=df['C'].str.lower()
df['C']=df['C'].str.replace(" ","")

In [410]:
df

         A    B     C    D  기본포함여부  문자길이
0  데이터 시각화  100  abcd  데이터   False     7
1   기본 학습서   20  abcd   기본    True     6
2  퇴근 후 열공   30  abcd   퇴근   False     7

In [411]:
df['C'].str[1:3]

0    bc
1    bc
2    bc
Name: C, dtype: object

In [412]:
df['C'].str[2:3]

0    c
1    c
2    c
Name: C, dtype: object

In [413]:
df['C'][1:2]

1    abcd
Name: C, dtype: object

In [417]:
import pandas as pd
df=pd.read_csv('cafe4.csv')

In [418]:
df

   Unnamed: 0     메뉴    가격   칼로리    원산지    이벤트가
0           0   카페라떼  5000   110   콜롬비아     NaN
1           1  아메리카노  5500   250   과테말라  1000.0
2           2   카푸치노  5000   110   과테말라  1000.0
3           3  에스프레소  4000    20   과테말라     NaN
4           4    밀크티  5900   210   과테말라     NaN
5           5     녹차  5300     0   대한민국     NaN
6           6   딴짓커피  3000  1100  코스타리카     NaN

In [420]:
df['메뉴'].str.len()

0    4
1    5
2    4
3    5
4    3
5    2
6    4
Name: 메뉴, dtype: int64

In [421]:
print(len(df))

7

In [422]:
df.shape

(7, 6)

In [423]:
cond=df['가격']>5000

In [424]:
cond

0    False
1     True
2    False
3    False
4     True
5     True
6    False
Name: 가격, dtype: bool

In [426]:
sum(cond)

3

In [427]:
len(df[cond])

3

In [428]:
df.sum(numeric_only=True)

Unnamed: 0       21.0
가격            33700.0
칼로리            1800.0
이벤트가           2000.0
dtype: float64

In [431]:
df

   Unnamed: 0     메뉴    가격   칼로리    원산지    이벤트가
0           0   카페라떼  5000   110   콜롬비아     NaN
1           1  아메리카노  5500   250   과테말라  1000.0
2           2   카푸치노  5000   110   과테말라  1000.0
3           3  에스프레소  4000    20   과테말라     NaN
4           4    밀크티  5900   210   과테말라     NaN
5           5     녹차  5300     0   대한민국     NaN
6           6   딴짓커피  3000  1100  코스타리카     NaN

In [434]:
df=df.T

In [435]:
df

               0       1       2      3     4     5      6
Unnamed: 0     0       1       2      3     4     5      6
메뉴          카페라떼   아메리카노    카푸치노  에스프레소   밀크티    녹차   딴짓커피
가격          5000    5500    5000   4000  5900  5300   3000
칼로리          110     250     110     20   210     0   1100
원산지         콜롬비아    과테말라    과테말라   과테말라  과테말라  대한민국  코스타리카
이벤트가         NaN  1000.0  1000.0    NaN   NaN   NaN    NaN

In [436]:
df.sum(axis=1,numeric_only=True)

Unnamed: 0    0.0
메뉴            0.0
가격            0.0
칼로리           0.0
원산지           0.0
이벤트가          0.0
dtype: float64

In [437]:
df=pd.read_csv('cafe4.csv')

In [438]:
df

   Unnamed: 0     메뉴    가격   칼로리    원산지    이벤트가
0           0   카페라떼  5000   110   콜롬비아     NaN
1           1  아메리카노  5500   250   과테말라  1000.0
2           2   카푸치노  5000   110   과테말라  1000.0
3           3  에스프레소  4000    20   과테말라     NaN
4           4    밀크티  5900   210   과테말라     NaN
5           5     녹차  5300     0   대한민국     NaN
6           6   딴짓커피  3000  1100  코스타리카     NaN

In [441]:
df.sum(axis=1,numeric_only=True)

0    5110.0
1    6751.0
2    6112.0
3    4023.0
4    6114.0
5    5305.0
6    4106.0
dtype: float64

In [442]:
df

   Unnamed: 0     메뉴    가격   칼로리    원산지    이벤트가
0           0   카페라떼  5000   110   콜롬비아     NaN
1           1  아메리카노  5500   250   과테말라  1000.0
2           2   카푸치노  5000   110   과테말라  1000.0
3           3  에스프레소  4000    20   과테말라     NaN
4           4    밀크티  5900   210   과테말라     NaN
5           5     녹차  5300     0   대한민국     NaN
6           6   딴짓커피  3000  1100  코스타리카     NaN

In [443]:
df=pd.read_csv('cafe4.csv')

In [444]:
df

   Unnamed: 0     메뉴    가격   칼로리    원산지    이벤트가
0           0   카페라떼  5000   110   콜롬비아     NaN
1           1  아메리카노  5500   250   과테말라  1000.0
2           2   카푸치노  5000   110   과테말라  1000.0
3           3  에스프레소  4000    20   과테말라     NaN
4           4    밀크티  5900   210   과테말라     NaN
5           5     녹차  5300     0   대한민국     NaN
6           6   딴짓커피  3000  1100  코스타리카     NaN

In [445]:
df.to_csv('cafe4.csv',index=None)

In [448]:
df=pd.read_csv('cafe4.csv',index_col=0)

In [449]:
df

               메뉴    가격   칼로리    원산지    이벤트가
Unnamed: 0
0            카페라떼  5000   110   콜롬비아     NaN
1           아메리카노  5500   250   과테말라  1000.0
2            카푸치노  5000   110   과테말라  1000.0
3           에스프레소  4000    20   과테말라     NaN
4             밀크티  5900   210   과테말라     NaN
5              녹차  5300     0   대한민국     NaN
6            딴짓커피  3000  1100  코스타리카     NaN

In [450]:
cond=df['가격'].quantile(.25)>df['가격']

In [451]:
df[cond]

               메뉴    가격   칼로리    원산지  이벤트가
Unnamed: 0
3           에스프레소  4000    20   과테말라   NaN
6            딴짓커피  3000  1100  코스타리카   NaN

In [452]:
cond=df['가격']>df['가격'].quantile(.75)

In [453]:
df[cond]

               메뉴    가격  칼로리   원산지    이벤트가
Unnamed: 0
1           아메리카노  5500  250  과테말라  1000.0
4             밀크티  5900  210  과테말라     NaN

In [457]:
df['원산지'].mode()[0]

'과테말라'

In [458]:
df['가격'].idxmax()

np.int64(4)

In [459]:
df['가격'].idxmin()

np.int64(6)

In [461]:
max_ind=df['가격'].idxmax()

In [462]:
max_ind

np.int64(4)

In [465]:
df.loc[max_ind]['메뉴']

'밀크티'