<a href="https://colab.research.google.com/github/gumurytv/bigdataCert/blob/main/%EB%B9%85%EB%B6%84%EA%B8%B0_%EC%8B%A4%EA%B8%B0_PART1_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
menu=pd.Series(['비빔밥','김치찌개','된장찌개'])

In [ ]:
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [ ]:
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [ ]:
price=pd.Series([10000,9000,8000])

In [ ]:
price

0    10000
1     9000
2     8000
dtype: int64

In [ ]:
df=pd.DataFrame({'메뉴':['비빔밥','김치찌개','된장찌개'],
                 '가격':[10000,9000,8000],
                 '원산지':['국내산','국내산','국내산']})

In [ ]:
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [ ]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [ ]:
df.'메뉴'

SyntaxError: invalid syntax (2931634542.py, line 1)

In [ ]:
df.메뉴

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [ ]:
df[['메뉴']]

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [ ]:
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [ ]:
df[['메뉴','가격']]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [ ]:
cols=['메뉴','가격']

In [ ]:
df[col]

NameError: name 'col' is not defined

In [ ]:
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [ ]:
type[df]

type[     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산]

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
print('df:',type(df))

df: <class 'pandas.core.frame.DataFrame'>

In [ ]:
df=pd.DataFrame({
    '메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    '가격':[4500,5000,5500,5000,4000,5900,5300],
    '칼로리':[10,110,250,110,20,210,0]
})

In [ ]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [ ]:
df_to.csv('temp.csv')

NameError: name 'df_to' is not defined

In [ ]:
df.to_csv('temp.csv')

In [ ]:
temp_df=pd.read_csv('temp.csv')

In [ ]:
temp_df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [ ]:
df.to_csv('cafe.csv',index=False)

In [ ]:
df=pd.read_csv('cafe.csv')

In [ ]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [ ]:
df.shape

(7, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [ ]:
df.corr(numeric=Ture)

NameError: name 'Ture' is not defined

In [ ]:
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [ ]:
df_car=pd.DataFrame({'car':['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
                  'size':['S','M','S','S','M','M','L','S','S','M','S']})

In [ ]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [ ]:
df_car

      car size
0   Sedan    S
1     SUV    M
2   Sedan    S
3     SUV    S
4     SUV    M
5     SUV    M
6   Sedan    L
7   Sedan    S
8   Sedan    S
9   Sedan    M
10  Sedan    S

In [ ]:
df_car.head(3)

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S

In [ ]:
df_car.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [ ]:
df_car.nunique()

car     2
size    3
dtype: int64

In [ ]:
print(df_car['car'].unique())

['Sedan' 'SUV']

In [ ]:
print(df_car['size'].unique())

['S' 'M' 'L']

In [ ]:
df_car['car'].value_counts()

car
Sedan    7
SUV      4
Name: count, dtype: int64

In [ ]:
df.value_counts()

메뉴     가격    칼로리
녹차     5300  0      1
밀크티    5900  210    1
아메리카노  4500  10     1
에스프레소  4000  20     1
카페라떼   5000  110    1
카페모카   5500  250    1
카푸치노   5000  110    1
Name: count, dtype: int64

In [ ]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [ ]:
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [ ]:
df_car.describe()

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [ ]:
df.describe(include='0')

TypeError: data type '' not understood

In [ ]:
data={
    '메뉴':['아메리카노','카페라떼','카페모카','카푸치노','에스프레소','밀크티','녹차'],
    '가격':[4500,5000,5500,5000,4000,5900,5300],
    '칼로리':['10','110','250','110','20','210','0']
}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [ ]:
data

{'메뉴': ['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
 '가격': [4500, 5000, 5500, 5000, 4000, 5900, 5300],
 '칼로리': ['10', '110', '250', '110', '20', '210', '0']}

In [ ]:
df['가격']=df['가격'].astype('int')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [ ]:
df['칼로리']=df['칼로리'].astype('float')

In [ ]:
ㅇㄹ

NameError: name 'ᄋᄅ' is not defined

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

In [ ]:
df=pd.read_csv('cafe.csv')

In [ ]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [ ]:
df['new']=0

In [ ]:
df.head()

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0
2   카페모카  5500  250    0
3   카푸치노  5000  110    0
4  에스프레소  4000   20    0

In [ ]:
discount=0.2

In [ ]:
df['할인가']=df['가격']*(1-discount)

In [ ]:
df

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0
2   카페모카  5500  250    0  4400.0
3   카푸치노  5000  110    0  4000.0
4  에스프레소  4000   20    0  3200.0
5    밀크티  5900  210    0  4720.0
6     녹차  5300    0    0  4240.0

In [ ]:
df=pd.read_csv('cafe.csv')

In [ ]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [ ]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [ ]:
df.drop(1,axis=0,inplace=True)

In [ ]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [ ]:
df=df.drop('메뉴',axis=1)

In [ ]:
df

     가격  칼로리
0  4500   10
2  5500  250
3  5000  110
4  4000   20
5  5900  210
6  5300    0

In [ ]:
df=pd.read_csv('cafe.csv')

In [ ]:
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [ ]:
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [ ]:
df.loc[1,'가격']

np.int64(5000)

In [ ]:
df.loc[:,'가격']

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [ ]:
df.loc[2,'메뉴':'칼로리']

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [ ]:
df.loc[2,['메뉴','칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [ ]:
df.loc[1:3,['메뉴','칼로리']]

     메뉴  칼로리
1  카페라떼  110
2  카페모카  250
3  카푸치노  110